import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "earliest-run/the-moon-clocks-out",
    kind: "earliest-run",
    form: "verse",
    band: "any",
    mood: "nocturnal",
    slots: ["clock"],
    introduces: ["the-moon"],
    lines: [
      { text: "{clock}. In the morning. The dark kind. The hush." },
      { text: "No birds on the clock yet. No cars. No rush." },
      { text: "The sun wasn't up — not a glimmer, not half." },
      { text: "The moon did a double take. I heard it laugh." },
      { text: "" },
      { text: "\"You're early,\" it said. \"Even I'm going to bed.\"" },
      { text: "\"I know,\" I told it. \"Sleep tight, sleepyhead.\"" },
      { text: "And I ran through streets that the day hadn't dressed." },
      { text: "The world before breakfast is mine. (I checked. Yes.)" },
    ],
  },
  {
    id: "earliest-run/passing-my-own-sleep",
    kind: "earliest-run",
    form: "verse",
    band: "any",
    mood: "absurd",
    slots: ["clock"],
    lines: [
      { text: "I set the alarm for {clock}. It stared." },
      { text: "It said, \"You're aware that's not morning?\" (It's scared.)" },
      { text: "It rang like a whisper, in case I'd forget." },
      { text: "I was up. I was dressed. I was out. It rang yet." },
      { text: "" },
      { text: "Somewhere mid-run, in the streetlight glow," },
      { text: "I passed my own sleep, still walking home, slow." },
      { text: "It waved. I waved back. We agreed not to fight:" },
      { text: "I get the mornings. It keeps the night." },
    ],
  },
  {
    id: "earliest-run/first-in-line",
    kind: "earliest-run",
    form: "verse",
    band: "any",
    mood: "steady",
    slots: ["clock"],
    lines: [
      { text: "The day is a shop that unlocks before dawn." },
      { text: "Most customers shuffle in yawning, at nine." },
      { text: "By then all the best stuff is thoroughly gone." },
      { text: "But me? At {clock} I was first in the line." },
      { text: "" },
      { text: "I got the last quiet, the first pink of sky," },
      { text: "the streets while still smooth, the air while still shy." },
      { text: "The rest of you got what you got. Don't blame me." },
      { text: "(The day restocks nightly. Come early. It's free.)" },
    ],
  },
  {
    id: "earliest-run/hauling-up-the-sun",
    kind: "earliest-run",
    form: "verse",
    band: "any",
    mood: "absurd",
    slots: ["clock"],
    lines: [
      { text: "They teach you the sun rises all on its own —" },
      { text: "by physics, by orbits, by spins finely honed." },
      { text: "But I was out running at {clock}, and I say" },
      { text: "SOMEBODY has to go fetch it each day." },
      { text: "" },
      { text: "I felt something catch on my shoe at the bend," },
      { text: "and the sky started lifting, end over end." },
      { text: "You're welcome for morning. No, really, it's fine." },
      { text: "(Tomorrow it's YOUR turn. I left you the line.)" },
    ],
  },
  {
    id: "earliest-run/first-footprints",
    kind: "earliest-run",
    form: "verse",
    band: "any",
    mood: "quiet",
    slots: ["clock"],
    lines: [
      {
        branch: {
          variants: [
            {
              when: { season: ["winter"] },
              lines: [
                { text: "At {clock}, with frost on the lawn," },
                { text: "my steps were the first ones printed on dawn." },
              ],
            },
            {
              when: { season: ["monsoon"] },
              lines: [
                { text: "At {clock}, in leftover rain," },
                { text: "my steps wrote the first line on the wet lane." },
              ],
            },
          ],
          default: [
            { text: "At {clock}, in dew on the ground," },
            { text: "my steps were the first anywhere around." },
          ],
        },
      },
      { text: "First footprints! All mine! A whole town's worth of street" },
      { text: "unstepped-on, unprinted, and bought by my feet." },
      { text: "" },
      { text: "So when the day happened — the crowds and the fuss —" },
      { text: "it happened on top of what started with us." },
      { text: "Tomorrow the sidewalks reset, blank and new," },
      { text: "and whoever runs first signs the day. (Could be you.)" },
    ],
  },
  {
    id: "earliest-run/the-secret-town",
    kind: "earliest-run",
    form: "verse",
    band: "any",
    mood: "nocturnal",
    slots: ["clock"],
    lines: [
      { text: "There's a secret town underneath this one." },
      { text: "It only exists before the day's begun:" },
      { text: "the bakery breathing its first warm bread," },
      { text: "the streetlights bowing as they go off to bed," },
      { text: "a cat on patrol with a clipboard stare," },
      { text: "and nobody — nobody — no one else there." },
      { text: "" },
      { text: "I'd tell you what time it unlocks... but then" },
      { text: "you'd be there. At {clock}. And it's mine till ten." },
    ],
  },
];
