import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "earliest-run/the-alarm-and-the-dark",
    kind: "earliest-run",
    form: "quatrain",
    band: "any",
    mood: "nocturnal",
    slots: [],
    lines: [
      { text: "The alarm went off inside the solid dark." },
      { text: "No bird agreed with it. No light took its side." },
      { text: "You, outvoted, rose against the room" },
      { text: "and met the morning early, before it was made." },
    ],
  },
  {
    id: "earliest-run/streetlights-off-the-clock",
    kind: "earliest-run",
    form: "quip",
    band: "any",
    mood: "quiet",
    slots: ["time"],
    lines: [
      { text: "At {time} the streetlights were still on shift." },
      { text: "They watched you pass and yawned themselves to gray." },
      { text: "You beat the sun to work. The sun heard about it." },
    ],
  },
  {
    id: "earliest-run/letter-from-the-early-dark",
    kind: "earliest-run",
    form: "letter",
    band: "any",
    mood: "nocturnal",
    slots: [],
    lines: [
      { text: "Dear early riser, from the dark that's still left:" },
      { text: "" },
      { text: "Most people never meet me. You keep coming." },
      { text: "You've seen the hour the world forgets to lock." },
      { text: "You know the quiet has a floor to stand on." },
      { text: "I won't pretend I make it easy. I don't." },
      { text: "" },
      { text: "But no one owns a morning like who wakes it. — dark" },
    ],
  },
  {
    id: "earliest-run/notice-the-world-was-shut",
    kind: "earliest-run",
    form: "notice",
    band: "any",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "NOTICE: The world was closed at that hour." },
      { text: "The birds had not yet opened. Nor the light." },
      { text: "Management was asleep and left no key." },
      { text: "You went out through the dark, which stays unlocked," },
      { text: "and ran the empty aisles of the whole town." },
    ],
  },
  {
    id: "earliest-run/who-else-was-up",
    kind: "earliest-run",
    form: "list",
    band: "any",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "The full census of the awake, at that hour:" },
      { text: "one baker, losing an argument with dough;", indent: 1 },
      { text: "one nurse, going the other way, more tired;", indent: 1 },
      { text: "a cat conducting business of its own;", indent: 1 },
      { text: "the moon, off duty, hanging around regardless;", indent: 1 },
      { text: "and you, the only one who had chosen it.", indent: 1 },
    ],
  },
  {
    id: "earliest-run/you-and-the-warm-bed",
    kind: "earliest-run",
    form: "dialogue",
    band: "any",
    mood: "sheepish",
    slots: [],
    lines: [
      { text: "Stay, said the bed. I'm warm. It's still the night.", voice: 1 },
      { text: "It's technically the morning, you replied.", voice: 2 },
      { text: "Technically, the bed scoffed, is a cold word.", voice: 1 },
      { text: "You'll be so tired. You'll regret this, it tried.", voice: 1 },
      { text: "I never have yet, you said, and found the floor.", voice: 2 },
      { text: "The bed stayed warm all day, to prove its point.", voice: 1 },
    ],
  },
  {
    id: "earliest-run/spell-against-the-snooze",
    kind: "earliest-run",
    form: "spell",
    band: "any",
    mood: "steady",
    slots: [],
    lines: [
      { text: "For the war against the snooze, fought lying down:" },
      { text: "do not negotiate; the bed will always win." },
      { text: "Move one foot to the cold part of the floor." },
      { text: "The rest of you, outraged, will follow it out." },
      { text: "Don't think about the miles. Think about the door." },
      { text: "Everything past the door agrees to happen." },
    ],
  },
  {
    id: "earliest-run/the-edge-of-the-light",
    kind: "earliest-run",
    form: "concrete",
    band: "any",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "dark", indent: 0 },
      { text: "still dark", indent: 0 },
      { text: "dark", indent: 1 },
      { text: "a thread of gray", indent: 1 },
      { text: "a seam of pink", indent: 2 },
      { text: "the whole east", indent: 2 },
      { text: "coming apart", indent: 3 },
      { text: "quietly at first", indent: 3 },
      { text: "then all at once —", indent: 3 },
      { text: "and you already out in it.", indent: 3 },
    ],
  },
];
