import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "false-starts/changed-its-mind",
    kind: "false-starts",
    form: "quip",
    band: "any",
    mood: "absurd",
    slots: [],
    lines: [
      { text: "A false start is a run that changed its mind." },
      { text: "It got dressed. It stood at the door. It reconsidered." },
      { text: "That is still further than the ones who never rose." },
    ],
  },
  {
    id: "false-starts/the-shape-of-almost",
    kind: "false-starts",
    form: "quatrain",
    band: "any",
    mood: "steady",
    slots: [],
    lines: [
      { text: "You laced up twice and sat back down again." },
      { text: "The couch said something reasonable and warm." },
      { text: "This is not a failure. This is a rehearsal —" },
      { text: "the body practicing the shape of almost." },
    ],
  },
  {
    id: "false-starts/you-and-the-couch",
    kind: "false-starts",
    form: "dialogue",
    band: "small",
    mood: "sheepish",
    slots: [],
    lines: [
      { text: "Where are you going? asked the couch, alarmed.", voice: 1 },
      { text: "Out for a run, you said, without conviction.", voice: 2 },
      { text: "You could also stay, it offered, being soft.", voice: 1 },
      { text: "It made three excellent, upholstered points.", voice: 1 },
      { text: "You heard them out. You owed it that, at least.", voice: 2 },
      { text: "Then you sat, and the run became a Thursday plan.", voice: 2 },
    ],
  },
  {
    id: "false-starts/no-fault-found",
    kind: "false-starts",
    form: "notice",
    band: "small",
    mood: "absurd",
    slots: ["count"],
    lines: [
      { text: "NO FAULT FOUND, reads the report on {count} attempts." },
      { text: "Each one got as far as intending, and stopped." },
      { text: "Intending, the Department notes, is where runs are born." },
      { text: "No run was harmed. Several were merely postponed." },
      { text: "Case closed, with sympathy, and left slightly open." },
    ],
  },
  {
    id: "false-starts/ways-it-declined",
    kind: "false-starts",
    form: "list",
    band: "medium",
    mood: "absurd",
    slots: [],
    lines: [
      { text: "Ways the run declined to begin today:" },
      { text: "the rain, which had opinions;", indent: 1 },
      { text: "the left shoe, hiding, as it does;", indent: 1 },
      { text: "a very good reason, since forgotten;", indent: 1 },
      { text: "the sudden, urgent need to reorganize a drawer;", indent: 1 },
      { text: "and honestly, mostly, the warmth of being still.", indent: 1 },
    ],
  },
  {
    id: "false-starts/note-from-the-driveway",
    kind: "false-starts",
    form: "letter",
    band: "medium",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "Re: the run you meant to take this morning." },
      { text: "" },
      { text: "The driveway writes to say there are no hard feelings." },
      { text: "You made it out as far as me, and paused," },
      { text: "and read the sky, and found it wanting, and withdrew." },
      { text: "I have seen this many times. The road is patient." },
      { text: "" },
      { text: "Come back when the sky is more agreeable. — the driveway" },
    ],
  },
  {
    id: "false-starts/blessing-for-the-ones-that-didnt",
    kind: "false-starts",
    form: "spell",
    band: "large",
    mood: "steady",
    slots: [],
    lines: [
      { text: "Bless the runs that got as far as the coat." },
      { text: "Bless the ones undone by a single cloud." },
      { text: "They are not nothing. They are the body learning" },
      { text: "that the door is a thing that opens either way." },
      { text: "Forgive the false start. It was still a start." },
      { text: "Keep the shoes by the door. Tomorrow is a door too." },
    ],
  },
  {
    id: "false-starts/out-and-back-again",
    kind: "false-starts",
    form: "concrete",
    band: "large",
    mood: "absurd",
    slots: [],
    lines: [
      { text: "out the door", indent: 0 },
      { text: "down the steps", indent: 1 },
      { text: "to the gate", indent: 2 },
      { text: "and then —", indent: 3 },
      { text: "a pause", indent: 2 },
      { text: "a rethink", indent: 1 },
      { text: "and back", indent: 0 },
      { text: "up the steps", indent: 0 },
      { text: "warm again.", indent: 0 },
    ],
  },
];
