import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "false-starts/world-class-beginner",
    kind: "false-starts",
    form: "verse",
    band: "any",
    mood: "sheepish",
    slots: ["count"],
    lines: [
      { text: "I'm a world-class beginner. A starter supreme." },
      { text: "My first fifty meters? Olympic. A dream." },
      { text: "It's the next fifty meters where trouble begins:" },
      { text: "a shoelace. A raindrop. A bee with two grins." },
      { text: "" },
      { text: "{count} launches. {count} returns." },
      { text: "The doormat's worn out from my quick U-turns." },
      { text: "But here's what the quitters will never have known:" },
      { text: "I've had {count} more starts than the kids who stayed home." },
    ],
  },
  {
    id: "false-starts/the-bee",
    kind: "false-starts",
    form: "verse",
    band: "any",
    mood: "absurd",
    slots: ["clock"],
    lines: [
      { text: "At {clock} I burst out the door like a flare," },
      { text: "shoes tied, chin up, elbows slicing the air —" },
      { text: "a hundred whole meters of glory and speed!" },
      { text: "Then I saw the bee." },
      { text: "" },
      { text: "The bee didn't chase me. Bees rarely do." },
      { text: "But you can't prove that to the back of my shoe." },
      { text: "Tomorrow, same time, I'll be brave, greatest ever." },
      { text: "(Unless there's the bee. Or a wasp. Or weather.)" },
    ],
  },
  {
    id: "false-starts/how-to-end-a-run",
    kind: "false-starts",
    form: "list",
    band: "any",
    mood: "sheepish",
    slots: ["count"],
    lines: [
      { text: "How to end a run in under a minute:" },
      { text: "Remember the oven (was anything in it?);", indent: 1 },
      { text: "Detect, in your sock, one grain of grit;", indent: 1 },
      { text: "Say \"warm-up walk\" and just... commit;", indent: 1 },
      { text: "See a cloud that seems personal. Quit;", indent: 1 },
      { text: "" },
      { text: "I know all {count} exits by heart." },
      { text: "But watch me — I keep lining up at the start." },
      { text: "The starting's the habit. The finish will come." },
      { text: "(Starts are the drumroll. Someday: the drum.)" },
    ],
  },
  {
    id: "false-starts/return-policy",
    kind: "false-starts",
    form: "verse",
    band: "any",
    mood: "absurd",
    slots: ["count"],
    lines: [
      { text: "The road has a policy, prominently signed:" },
      { text: "ALL RUNS RETURNABLE. NO QUESTIONS. THAT'S FINE." },
      { text: "So I've made some returns. Well — {count}, to date." },
      { text: "\"Defective,\" I tell it. \"Too puddly.\" \"Too late.\"" },
      { text: "" },
      { text: "The road takes them back with a nod, every time," },
      { text: "and re-shelves the meters. No fuss and no fine." },
      { text: "Though stamped on my last one, in road-colored ink:" },
      { text: "\"RETURNED TOO OFTEN. TRY KEEPING ONE. — wink\"" },
    ],
  },
  {
    id: "false-starts/shortest-epic",
    kind: "false-starts",
    form: "verse",
    band: "small",
    mood: "absurd",
    slots: [],
    lines: [
      { text: "The bards sing of marathons. Fine. Let them sing." },
      { text: "My epic is shorter. My epic's a spring:" },
      { text: "one leap off the porch — form! majesty! grace! —" },
      { text: "and a landing (the sprinkler was on) in first place." },
      { text: "" },
      { text: "Some medals take hours. Mine took one bound." },
      { text: "The judges (two squirrels) said I \"stuck it, then drowned.\"" },
      { text: "An epic's an epic, whatever the length." },
      { text: "(Mine's just very... concentrated. Like strength.)" },
    ],
  },
  {
    id: "false-starts/dress-rehearsals",
    kind: "false-starts",
    form: "verse",
    band: "large",
    mood: "steady",
    slots: ["count"],
    lines: [
      { text: "{count} short ones. The neighbors keep score." },
      { text: "They see me charge out and charge back through the door." },
      { text: "They think that I'm losing. They chuckle. They grin." },
      { text: "They don't know rehearsals. I'm practicing WIN." },
      { text: "" },
      { text: "Opening night's coming. I don't know the date." },
      { text: "Some morning these legs will just... not hesitate," },
      { text: "and the run will go on, and on, past the town." },
      { text: "(You laughed at rehearsals. The show won't sit down.)" },
    ],
  },
];
