import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "fastest-run/the-wind-took-notes",
    kind: "fastest-run",
    form: "quatrain",
    band: "any",
    mood: "absurd",
    slots: [],
    lines: [
      { text: "The wind was minding its own business, mostly," },
      { text: "when you went by and parted it in two." },
      { text: "It has not fully recovered its composure." },
      { text: "It still leans east on Tuesdays, thinking of you." },
    ],
  },
  {
    id: "fastest-run/spell-for-going-fast",
    kind: "fastest-run",
    form: "spell",
    band: "any",
    mood: "steady",
    slots: [],
    lines: [
      { text: "To go fast, first agree to be a rumor." },
      { text: "Let the ground hear you before it sees you coming." },
      { text: "Spend the breath. Don't save it for the photo." },
      { text: "Forget the arms; they will sort themselves out." },
      { text: "Lean like you mean to fall, and simply don't." },
    ],
  },
  {
    id: "fastest-run/notice-a-personal-record",
    kind: "fastest-run",
    form: "notice",
    band: "small",
    mood: "sheepish",
    slots: [],
    lines: [
      { text: "NOTICE: A personal record has occurred." },
      { text: "It is personal. It is, we stress, a record." },
      { text: "No one else on this whole earth will ever care" },
      { text: "that today you beat a slightly slower you." },
      { text: "The slightly slower you is very impressed." },
    ],
  },
  {
    id: "fastest-run/what-the-watch-said",
    kind: "fastest-run",
    form: "dialogue",
    band: "small",
    mood: "absurd",
    slots: [],
    lines: [
      { text: "Was that fast? you gasped. Tell me that was fast.", voice: 1 },
      { text: "Faster than yesterday, the watch allowed.", voice: 2 },
      { text: "Faster than the mailman? Faster than a bee?", voice: 1 },
      { text: "Let us not, said the watch, oversell the moment.", voice: 2 },
      { text: "It never says fast, you sulked. It just won't.", voice: 1 },
      { text: "But quietly it logged it twice, for safekeeping.", voice: 2 },
    ],
  },
  {
    id: "fastest-run/shoes-took-off",
    kind: "fastest-run",
    form: "quip",
    band: "medium",
    mood: "absurd",
    slots: ["pace"],
    lines: [
      { text: "The shoes took off at {pace} flat." },
      { text: "You were, of course, inside them." },
      { text: "There's still no legal precedent" },
      { text: "for who should get the medal." },
    ],
  },
  {
    id: "fastest-run/letter-to-the-slow-days",
    kind: "fastest-run",
    form: "letter",
    band: "medium",
    mood: "steady",
    slots: [],
    lines: [
      { text: "Dear slow days, the ones I ran through actual mud:" },
      { text: "" },
      { text: "I'm writing from a fast one just to say thanks." },
      { text: "You were not wasted. You were where the legs" },
      { text: "learned what to save and what to simply spend." },
      { text: "Today ran quick because you all ran long." },
      { text: "" },
      { text: "I won't forget you. Well — I might. But not on purpose." },
    ],
  },
  {
    id: "fastest-run/inventory-of-the-fast-mile",
    kind: "fastest-run",
    form: "list",
    band: "large",
    mood: "triumphant",
    slots: ["pace"],
    lines: [
      { text: "Everything the fast mile left behind it:" },
      { text: "your own held breath, still hanging in the air;", indent: 1 },
      { text: "a dog mid-bark, now barking at your ghost;", indent: 1 },
      { text: "three parked cars you're fairly sure you lapped;", indent: 1 },
      { text: "the word later, dropped right where you were standing;", indent: 1 },
      { text: "and a clock that read {pace} and could not," },
      { text: "for the life of it, believe the arithmetic.", indent: 1 },
    ],
  },
  {
    id: "fastest-run/blur",
    kind: "fastest-run",
    form: "concrete",
    band: "large",
    mood: "absurd",
    slots: [],
    lines: [
      { text: "you", indent: 0 },
      { text: "were", indent: 0 },
      { text: "here —", indent: 1 },
      { text: "then a smear of you,", indent: 2 },
      { text: "then the idea of you,", indent: 3 },
      { text: "then just the wind", indent: 3 },
      { text: "hurrying to close", indent: 3 },
      { text: "the space you left.", indent: 3 },
    ],
  },
];
