import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "fastest-run/i-outran-my-shadow",
    kind: "fastest-run",
    form: "verse",
    band: "any",
    mood: "triumphant",
    slots: ["clock", "weekday"],
    introduces: ["shadow"],
    lines: [
      { text: "The dog at the corner is faster than me," },
      { text: "the bus is much faster, and so is the bee," },
      { text: "the kid down the block on her half-broken skates" },
      { text: "is faster — and she had to stop at the gates." },
      { text: "" },
      { text: "But {weekday} at {clock}, for one perfect mile," },
      { text: "I outran my shadow. I swear. By a smile." },
      { text: "Now it wants a rematch, and I said, \"Okay.\"" },
      { text: "It grinned and picked noon. ...I've been had, by the way." },
    ],
  },
  {
    id: "fastest-run/the-watch-went-shy",
    kind: "fastest-run",
    form: "verse",
    band: "any",
    mood: "absurd",
    slots: ["pace", "weekday"],
    introduces: ["the-watch"],
    lines: [
      { text: "My watch and I don't get along." },
      { text: "It thinks I'm slow. It's often wrong —" },
      { text: "it's ALWAYS wrong — okay, it's right," },
      { text: "but only 'cause it's wound up tight." },
      { text: "" },
      { text: "Then {weekday} came, and the numbers got low —" },
      { text: "{pace}?! — the watch double-checked it was so." },
      { text: "It hasn't nagged me since. It's shy." },
      { text: "(It thinks it broke that day. It didn't. That was I.)" },
    ],
  },
  {
    id: "fastest-run/downhill-confession",
    kind: "fastest-run",
    form: "verse",
    band: "any",
    mood: "sheepish",
    slots: [],
    lines: [
      { text: "The block declared me fastest kid." },
      { text: "I let them cheer. I never hid." },
      { text: "The record's real. The legs are true." },
      { text: "And yet, a fact I'll share with you:" },
      { text: "" },
      { text: "the whole way back was down a hill." },
      { text: "A big one. And I'm counting it still." },
    ],
  },
  {
    id: "fastest-run/my-brother-and-the-watch",
    kind: "fastest-run",
    form: "verse",
    band: "any",
    mood: "absurd",
    slots: ["pace"],
    lines: [
      { text: "My brother says turtles have lapped me before." },
      { text: "My brother says mailmen. My brother says DOORS." },
      { text: "So I handed my brother the watch and said, \"Time it.\"" },
      { text: "Then I ran like the fence had a fire behind it." },
      { text: "" },
      { text: "{pace}. He inspected it twice." },
      { text: "He shook it. He held it up close to him, like ice." },
      { text: "\"The watch must be broken.\" He sulked off to bed." },
      { text: "(The watch works fine. My brother's broken instead.)" },
    ],
  },
  {
    id: "fastest-run/the-wind-recruits",
    kind: "fastest-run",
    form: "verse",
    band: "large",
    mood: "triumphant",
    slots: ["pace"],
    lines: [
      { text: "The wind collects the fastest things:" },
      { text: "loose hats, cut kites, and pigeon wings," },
      { text: "lost homework pages, autumn leaves," },
      { text: "and anything with short, quick sleeves." },
      { text: "" },
      { text: "It clocked me at {pace} today." },
      { text: "It rattled the window. It wants me to play." },
      { text: "I'm flattered, wind, but let me be:" },
      { text: "you only recruit what you can't catch. (Me.)" },
    ],
  },
  {
    id: "fastest-run/nobody-gasped",
    kind: "fastest-run",
    form: "verse",
    band: "small",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "Nobody gasped. No trumpet played." },
      { text: "The grass stayed calm. The dog just stayed." },
      { text: "The world records are all intact," },
      { text: "and physics didn't even react." },
      { text: "" },
      { text: "But I was there inside my chest" },
      { text: "when it out-thumped its personal best." },
      { text: "The world keeps score in someone else's ink." },
      { text: "My score's in mine. (It's faster than you think.)" },
    ],
  },
];
