import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "first-run/new-shoes-know-nothing",
    kind: "first-run",
    form: "quatrain",
    band: "any",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "The shoes came out of the box believing nothing." },
      { text: "No hills yet. No weather. No idea of you." },
      { text: "They thought the world was flat and always kind." },
      { text: "You laced them up and taught them otherwise." },
    ],
  },
  {
    id: "first-run/road-introduces-itself",
    kind: "first-run",
    form: "quip",
    band: "any",
    mood: "steady",
    slots: [],
    lines: [
      { text: "The road cleared its throat and said: new one." },
      { text: "Then, quieter, so you wouldn't hear it:" },
      { text: "welcome. Take your time. I'll wait." },
    ],
  },
  {
    id: "first-run/letter-from-the-year",
    kind: "first-run",
    form: "letter",
    band: "any",
    mood: "steady",
    slots: ["year"],
    lines: [
      { text: "Dear whoever you are about to become," },
      { text: "" },
      { text: "You don't know it yet, standing in {year}," },
      { text: "but this is the short one. The nervous one." },
      { text: "The run where you check if anyone's watching." },
      { text: "(No one is. That's the secret. Go.)" },
      { text: "" },
      { text: "I've seen how this ends. I'm not allowed to say." },
      { text: "Only that you keep the shoes. Warmly, the calendar." },
    ],
  },
  {
    id: "first-run/notice-first-entry",
    kind: "first-run",
    form: "notice",
    band: "any",
    mood: "steady",
    slots: ["km"],
    lines: [
      { text: "NOTICE: One (1) first run has been logged." },
      { text: "Distance: {km} kilometers. Witnesses: none." },
      { text: "The Department regrets it cannot certify" },
      { text: "the exact moment a person becomes a runner." },
      { text: "It happened somewhere in the middle. Filed." },
    ],
  },
  {
    id: "first-run/list-what-it-didnt-know",
    kind: "first-run",
    form: "list",
    band: "any",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "What the first run did not know about itself:" },
      { text: "that it was first;", indent: 1 },
      { text: "that there would be others;", indent: 1 },
      { text: "that you would name none of them but this;", indent: 1 },
      { text: "that the finish was never once the point;", indent: 1 },
      { text: "that it would be kept for having been afraid.", indent: 1 },
    ],
  },
  {
    id: "first-run/two-minds-at-the-door",
    kind: "first-run",
    form: "dialogue",
    band: "any",
    mood: "sheepish",
    slots: [],
    lines: [
      { text: "Stay in, said the doubt. It's cold and far.", voice: 1 },
      { text: "It is, said the shoes. Also, it's a door.", voice: 2 },
      { text: "You'll be slow. You'll be seen. You'll be new.", voice: 1 },
      { text: "New, said the shoes, is just the word for start.", voice: 2 },
      { text: "The doubt tried once more and found the porch.", voice: 1 },
      { text: "The shoes were already halfway down the block.", voice: 2 },
    ],
  },
  {
    id: "first-run/spell-to-begin",
    kind: "first-run",
    form: "spell",
    band: "any",
    mood: "steady",
    slots: [],
    lines: [
      { text: "For the first step, when the whole thing seems too big:" },
      { text: "one shoe, and then, astonishingly, the other." },
      { text: "One breath you keep. One breath you spend." },
      { text: "Say the small true thing: I am going outside." },
      { text: "Repeat it till the door begins to believe you." },
      { text: "Repeat it till your own two feet do too." },
    ],
  },
  {
    id: "first-run/concrete-one-step",
    kind: "first-run",
    form: "concrete",
    band: "any",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "here", indent: 0 },
      { text: "is", indent: 1 },
      { text: "where", indent: 1 },
      { text: "it", indent: 2 },
      { text: "starts:", indent: 2 },
      { text: "one small foot", indent: 3 },
      { text: "put stubbornly", indent: 3 },
      { text: "in front of the last.", indent: 3 },
    ],
  },
];
