import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "first-run/the-street-woke-up",
    kind: "first-run",
    form: "verse",
    band: "any",
    mood: "absurd",
    slots: ["clock", "weekday"],
    lines: [
      { text: "The street and I had never met." },
      { text: "It thought that I was walking. (Yet.)" },
      { text: "It rolled out flat and gray and long," },
      { text: "and hummed a boring walking song." },
      { text: "" },
      {
        branch: {
          variants: [
            {
              when: { hourBand: ["dawn"] },
              lines: [
                { text: "Then {weekday}, {clock}, before the sun," },
                { text: "my feet leaned forward and declared us: RUN." },
              ],
            },
            {
              when: { hourBand: ["night"] },
              lines: [
                { text: "Then {weekday} night, at {clock}, in the dark," },
                { text: "my feet struck quick and bright, and made a spark." },
              ],
            },
          ],
          default: [
            { text: "Then {weekday} came, at {clock} on the dot," },
            { text: "my feet remembered something I forgot." },
          ],
        },
      },
      { text: "The street woke up. The street said, \"WHO?\"" },
      { text: "The street's still asking. (I am too.)" },
    ],
  },
  {
    id: "first-run/brand-new-shoes",
    kind: "first-run",
    form: "verse",
    band: "any",
    mood: "absurd",
    slots: ["km"],
    introduces: ["shoes"],
    lines: [
      { text: "My shoes were white as winter, white as glue," },
      { text: "as white as shoes that nothing happened to." },
      { text: "They squeaked with fear on every second stride:" },
      { text: "\"Go back! We're clean! We're beautiful inside!\"" },
      { text: "" },
      { text: "{km} kilometers later, splashed and gray," },
      { text: "they wouldn't squeak at anyone all day." },
      { text: "I heard them, though, that night beside the door," },
      { text: "whispering to the slippers: \"We want more.\"" },
    ],
  },
  {
    id: "first-run/chasing-the-bus",
    kind: "first-run",
    form: "verse",
    band: "any",
    mood: "sheepish",
    slots: [],
    lines: [
      { text: "I only meant to catch the bus." },
      { text: "The bus left early on. And thus" },
      { text: "began the chase: my legs, the street," },
      { text: "the flapping of escaping feet." },
      { text: "" },
      { text: "I never caught it. Never mind." },
      { text: "Six blocks along, I got behind" },
      { text: "a better thought, and chased that instead." },
      { text: "(The bus goes back and forth. I go ahead.)" },
    ],
  },
  {
    id: "first-run/things-i-was-sure-of",
    kind: "first-run",
    form: "list",
    band: "any",
    mood: "sheepish",
    slots: ["clock"],
    lines: [
      { text: "Things I knew for certain at {clock} that day:" },
      { text: "Runners are a different species, born that way.", indent: 1 },
      { text: "My knees are decorations. So are both my lungs.", indent: 1 },
      { text: "Kilometers eat beginners. (They have tongues.)", indent: 1 },
      { text: "The couch is my true home, and I should stay.", indent: 1 },
      { text: "" },
      { text: "Now cross out every line above. I ran anyway." },
    ],
  },
  {
    id: "first-run/ill-be-back-thursday",
    kind: "first-run",
    form: "verse",
    band: "any",
    mood: "steady",
    slots: [],
    lines: [
      { text: "The first kilometer lasted a year." },
      { text: "The second went by like a bad idea." },
      { text: "The third one — wait. There was no third." },
      { text: "I stopped. I wheezed. I gave my word:" },
      { text: "" },
      { text: "\"I'll be back Thursday.\" And the road," },
      { text: "which knows a promise from a load" },
      { text: "of hooey, creaked out: \"We'll see, we'll see.\"" },
      { text: "...It saw. On Thursday. There I was. (Me.)" },
    ],
  },
  {
    id: "first-run/the-hardest-part",
    kind: "first-run",
    form: "verse",
    band: "any",
    mood: "steady",
    slots: ["km"],
    lines: [
      { text: "The hardest part of any run" },
      { text: "is not the hills. It's not the sun." },
      { text: "It's not the dog on Baxter Street." },
      { text: "It's not your lungs. It's not your feet." },
      { text: "" },
      { text: "It's seven steps from couch to door." },
      { text: "I trained a month for those. Maybe more." },
      { text: "The other {km} kilometers? Free." },
      { text: "(The couch still hasn't forgiven me.)" },
    ],
  },
];
