import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "ghost-elevation/the-watch-insists",
    kind: "ghost-elevation",
    form: "quip",
    band: "any",
    mood: "absurd",
    slots: ["gain", "name"],
    lines: [
      { text: "The watch swears you climbed {gain} meters today," },
      { text: "up a phantom hill it named {name}." },
      { text: "The route was flat as a rumor. The watch insists." },
    ],
  },
  {
    id: "ghost-elevation/everyone-agrees",
    kind: "ghost-elevation",
    form: "quatrain",
    band: "any",
    mood: "absurd",
    slots: [],
    lines: [
      { text: "There was no hill. Everyone agrees there was no hill." },
      { text: "The ground was level. The map is very sure." },
      { text: "And yet your legs, and yet the satellite, report" },
      { text: "a climb that happened somewhere none of you were." },
    ],
  },
  {
    id: "ghost-elevation/believe-your-feet",
    kind: "ghost-elevation",
    form: "dialogue",
    band: "any",
    mood: "absurd",
    slots: [],
    lines: [
      { text: "You gained elevation, the GPS announced, brightly.", voice: 1 },
      { text: "On a flat loop? you said. Where? Show me the hill.", voice: 2 },
      { text: "I cannot show you the hill, it admitted, softly.", voice: 1 },
      { text: "The hill declines to appear on any map but mine.", voice: 1 },
      { text: "Then it isn't real, you said. It rose all the same.", voice: 2 },
      { text: "Believe the numbers, it whispered, or your feet.", voice: 1 },
    ],
  },
  {
    id: "ghost-elevation/public-denial",
    kind: "ghost-elevation",
    form: "notice",
    band: "any",
    mood: "absurd",
    slots: ["gain"],
    lines: [
      { text: "PUBLIC DENIAL: no hill exists at that location." },
      { text: "Surveyors were dispatched. Surveyors found flatness." },
      { text: "And yet {gain} meters of climb were logged, and stand." },
      { text: "The Department cannot explain it and has stopped trying." },
      { text: "File it under: the ground was up to something." },
    ],
  },
  {
    id: "ghost-elevation/evidence-for-the-hill",
    kind: "ghost-elevation",
    form: "list",
    band: "any",
    mood: "absurd",
    slots: [],
    lines: [
      { text: "Evidence for the hill that isn't there:" },
      { text: "a heaviness in the legs at the third streetlight;", indent: 1 },
      { text: "a view, briefly, that a flat road should not give;", indent: 1 },
      { text: "the satellite, sweating, insisting on its numbers;", indent: 1 },
      { text: "a cool wind that only blows on things with height;", indent: 1 },
      { text: "and the strong, sourceless feeling of having risen.", indent: 1 },
    ],
  },
  {
    id: "ghost-elevation/the-hill-that-isnt",
    kind: "ghost-elevation",
    form: "letter",
    band: "any",
    mood: "absurd",
    slots: ["gain", "name"],
    lines: [
      { text: "You cannot see me, but you climbed me anyway." },
      { text: "" },
      { text: "I am the hill that isn't. My name, if you like:" },
      { text: "{name}." },
      { text: "I gave you {gain} honest meters of going up." },
      { text: "That no one else can find me is between us." },
      { text: "Your legs believe in me. That has always been enough." },
      { text: "" },
      { text: "Elevationally yours, — the ghost" },
    ],
  },
  {
    id: "ghost-elevation/to-raise-a-hill",
    kind: "ghost-elevation",
    form: "spell",
    band: "any",
    mood: "absurd",
    slots: ["name"],
    lines: [
      { text: "To raise a hill where the map insists on none:" },
      { text: "run hard on level ground and do not look down." },
      { text: "Call the phantom climb up by its given name —" },
      { text: "{name} —" },
      { text: "and let your burning legs be the proof it needs." },
      { text: "The watch will swear to it. Let the watch swear." },
    ],
  },
  {
    id: "ghost-elevation/rises-out-of-nothing",
    kind: "ghost-elevation",
    form: "concrete",
    band: "any",
    mood: "absurd",
    slots: [],
    lines: [
      { text: "the road", align: "center" },
      { text: "runs flat", align: "center" },
      { text: "and flat", align: "center" },
      { text: "and flatter still —", align: "center" },
      { text: "and yet", align: "center" },
      { text: "here, on the graph,", align: "center" },
      { text: "a ghost hill", align: "center" },
      { text: "rises out of", align: "center" },
      { text: "nothing at all.", align: "center" },
    ],
  },
];
