import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "ghost-elevation/my-legs-made-it-up",
    kind: "ghost-elevation",
    form: "verse",
    band: "any",
    mood: "absurd",
    slots: ["gain", "weekday"],
    lines: [
      { text: "My town is a pancake. Officially flat." },
      { text: "The maps all agree, and the maps know that." },
      { text: "So WHERE, on a {weekday}, mid-run, did I find" },
      { text: "{gain} meters of UP? And what kind?" },
      { text: "" },
      { text: "I climbed it. It wasn't there Tuesday. I checked." },
      { text: "By Thursday: pancake. Nothing. Correct." },
      { text: "The town says I made it all up. And okay —" },
      { text: "my LEGS made it up. (They still ache to this day.)" },
    ],
  },
  {
    id: "ghost-elevation/entered-in-the-record",
    kind: "ghost-elevation",
    form: "verse",
    band: "any",
    mood: "steady",
    slots: ["name", "gain"],
    lines: [
      { text: "A mountain that vanishes still needs a name —" },
      { text: "or how would you prove that it ever became?" },
      { text: "So, entered in the record, in permanent pen:" },
      { text: "{name}.", align: "center" },
      { text: "Elevation: {gain}. Location: gone. When:" },
      { text: "one run, one witness. (The witness was me.)" },
      { text: "Some mountains live only in legs. Let them be." },
    ],
  },
  {
    id: "ghost-elevation/the-phantom-staircase",
    kind: "ghost-elevation",
    form: "verse",
    band: "any",
    mood: "nocturnal",
    slots: ["gain"],
    lines: [
      { text: "The ghost hill's a staircase with nobody's floors," },
      { text: "a stairwell to nowhere, no windows, no doors." },
      { text: "You climb and you climb and you carefully count:" },
      { text: "{gain} whole meters of phantom amount." },
      { text: "" },
      { text: "At the top there's no summit, no flag and no view —" },
      { text: "just regular street, and a winded-out you." },
      { text: "So why did I climb it? Come on. Be exact:" },
      { text: "(because it was THERE. And then... it wasn't. That's fact.)" },
    ],
  },
  {
    id: "ghost-elevation/interview-with-my-knees",
    kind: "ghost-elevation",
    form: "verse",
    band: "any",
    mood: "absurd",
    slots: ["gain"],
    lines: [
      { text: "REPORTER (me): \"So. The mountain. Was it real?\"" },
      { text: "KNEES: \"We refuse to answer. But here's how we feel:\"" },
      { text: "(A creak. A pop. A meaningful crack.)" },
      { text: "REPORTER: \"And would you two ever go back?\"" },
      { text: "" },
      { text: "KNEES: \"It was {gain} meters of stair.\"" },
      { text: "\"It vanished by Friday.\" \"It wasn't there.\"" },
      { text: "REPORTER: \"One last question, if that's all right...\"" },
      { text: "KNEES: \"NO MORE MOUNTAINS.\" (...We leave at first light.)" },
    ],
  },
  {
    id: "ghost-elevation/the-hill-heard-about-it",
    kind: "ghost-elevation",
    form: "verse",
    band: "any",
    mood: "steady",
    slots: ["gain"],
    coda: {
      requires: "the-hill",
      lines: [
        { text: "P.S. If you see the hill straining, don't laugh. Wave." },
        { text: "(It's been doing hill-ups. It wants to be brave.)" },
      ],
    },
    lines: [
      { text: "The regular hill heard about it, of course." },
      { text: "News travels through pavement with terrible force." },
      { text: "\"A MOUNTAIN?\" it rumbled. \"Right HERE? In THIS town?\"" },
      { text: "\"{gain} meters?! I'm barely a mound!\"" },
      { text: "" },
      { text: "I patted its sidewalk. \"You're plenty of climb.\"" },
      { text: "\"That thing came just once. You're here ALL the time.\"" },
      { text: "The hill settled down. But some nights, its slope" },
      { text: "practices steepness. (I've seen it. There's hope.)" },
    ],
  },
  {
    id: "ghost-elevation/proof",
    kind: "ghost-elevation",
    form: "verse",
    band: "any",
    mood: "sheepish",
    slots: ["gain", "weekday"],
    lines: [
      { text: "No photos exist. The receipts blew away." },
      { text: "The map shrugged its grid lines. The town wouldn't say." },
      { text: "My {weekday} mountain is filed under \"myth,\"" },
      { text: "\"tall tales,\" and \"kid, what'd you climb that hill WITH?\"" },
      { text: "" },
      { text: "But muscle believes what the maps call absurd." },
      { text: "({gain} meters. My legs took the word.)" },
      { text: "The proof's in the morning-after, plain as can be:" },
      { text: "I came down the stairs going \"ow,\" sideways. (See?)" },
    ],
  },
];
