import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "hill-beast/has-never-trained",
    kind: "hill-beast",
    form: "quip",
    band: "any",
    mood: "absurd",
    slots: ["name"],
    lines: [
      { text: "You put in a year. {name}" },
      { text: "has never trained a day. It doesn't stretch." },
      { text: "It is simply uphill, always, and it is winning." },
    ],
  },
  {
    id: "hill-beast/patient-refusal",
    kind: "hill-beast",
    form: "quatrain",
    band: "any",
    mood: "steady",
    slots: ["gain"],
    lines: [
      { text: "The beast is {gain} meters of patient refusal." },
      { text: "It does not hate you. Hatred takes attention." },
      { text: "It simply is, and asks that you become," },
      { text: "for a few hard minutes, something that can rise." },
    ],
  },
  {
    id: "hill-beast/only-that-you-mean-it",
    kind: "hill-beast",
    form: "dialogue",
    band: "small",
    mood: "steady",
    slots: [],
    lines: [
      { text: "You're back for more, the beast said, not unkindly.", voice: 1 },
      { text: "I respect you, you gasped. That's why I keep coming.", voice: 2 },
      { text: "Respect is the only thing I take, it said.", voice: 1 },
      { text: "Not your speed, not your pride. Only that you mean it.", voice: 1 },
      { text: "I mean it, you said, on the last and worst of it.", voice: 2 },
      { text: "Then rise, said the beast, and it let you to the top.", voice: 1 },
    ],
  },
  {
    id: "hill-beast/terms-as-posted",
    kind: "hill-beast",
    form: "notice",
    band: "small",
    mood: "steady",
    slots: ["gain", "name"],
    lines: [
      { text: "TERMS, posted by {name}:" },
      { text: "I am {gain} meters. I do not negotiate the number." },
      { text: "You may pass, on foot, and spend your breath to do it." },
      { text: "I keep no scores and hand out no medals." },
      { text: "Climb me for the climb, or do not climb at all." },
    ],
  },
  {
    id: "hill-beast/what-it-took-and-gave",
    kind: "hill-beast",
    form: "list",
    band: "medium",
    mood: "steady",
    slots: [],
    lines: [
      { text: "What the great hill took from you, and gave:" },
      { text: "took your breath, and gave it back in gulps;", indent: 1 },
      { text: "took your pace, and gave a slower, truer one;", indent: 1 },
      { text: "took the easy story you told about yourself;", indent: 1 },
      { text: "gave a harder one, with better standing in it;", indent: 1 },
      { text: "and kept, the way beasts do, the view up top.", indent: 1 },
    ],
  },
  {
    id: "hill-beast/felt-you-on-my-back",
    kind: "hill-beast",
    form: "letter",
    band: "medium",
    mood: "steady",
    slots: ["gain", "name"],
    lines: [
      { text: "I felt you on my back this morning. All {gain} meters." },
      { text: "" },
      { text: "You may call me by the name you gave me:" },
      { text: "{name}." },
      { text: "I have thrown down stronger and prouder than you." },
      { text: "Come in winter, if you dare. I am worse in winter." },
      { text: "" },
      { text: "Grave respect — {name}" },
    ],
  },
  {
    id: "hill-beast/before-you-climb",
    kind: "hill-beast",
    form: "spell",
    band: "large",
    mood: "steady",
    slots: ["name"],
    lines: [
      { text: "Before you climb, name the hill with respect:" },
      { text: "{name}." },
      { text: "Do not curse it on the way up; it hears everything." },
      { text: "Match your smallest steps to your steadiest breath." },
      { text: "Give it the whole of your attention. It earns that." },
      { text: "At the top, thank it. Then let it be a hill again." },
    ],
  },
  {
    id: "hill-beast/the-beast-rising",
    kind: "hill-beast",
    form: "concrete",
    band: "large",
    mood: "absurd",
    slots: [],
    lines: [
      { text: "you are on", indent: 0 },
      { text: "something's back", indent: 1 },
      { text: "and it is breathing", indent: 1 },
      { text: "a shoulder heaves", indent: 2 },
      { text: "then another shoulder", indent: 2 },
      { text: "the long spine", indent: 3 },
      { text: "climbing under you —", indent: 3 },
      { text: "until the beast grows bored", indent: 2 },
      { text: "and sets you, gently, on its head.", indent: 1 },
    ],
  },
];
