import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "hill-beast/a-personal-grudge",
    kind: "hill-beast",
    form: "verse",
    band: "any",
    mood: "steady",
    slots: ["times"],
    introduces: ["the-hill"],
    lines: [
      { text: "There's a hill on my route with a personal grudge." },
      { text: "I've climbed it {times} times. It refuses to budge." },
      { text: "Each visit it steepens a little bit more" },
      { text: "(it thinks I can't tell) then it evens the score." },
      { text: "" },
      { text: "We're rivals. We're enemies. Bitter. Sworn. True." },
      { text: "I shout at its slope and it huffs at my shoe." },
      { text: "But miss it one week and I oddly feel flat." },
      { text: "(You can't hate a hill {times} times without love. That's that.)" },
    ],
  },
  {
    id: "hill-beast/earned-a-name",
    kind: "hill-beast",
    form: "verse",
    band: "any",
    mood: "steady",
    slots: ["times", "name"],
    introduces: ["the-hill"],
    lines: [
      { text: "A hill you climb once is a stranger. That's all." },
      { text: "A hill you climb twice is a bump with some gall." },
      { text: "But {times} times up the same aching flank?" },
      { text: "That hill's earned a name and a rank:" },
      { text: "{name}.", align: "center" },
      { text: "" },
      { text: "Salute when you pass it. It's watching. It knows." },
      { text: "(It keeps its own count of my visits. It shows.)" },
    ],
  },
  {
    id: "hill-beast/my-coach-the-landform",
    kind: "hill-beast",
    form: "verse",
    band: "any",
    mood: "steady",
    slots: ["gain", "times"],
    lines: [
      { text: "My coach is a landform. I pay it in sweat." },
      { text: "It's mean and it's steady and doesn't forget." },
      { text: "It never says \"nice one.\" It never says \"rest.\"" },
      { text: "It just stands there, slanted, suggesting the test." },
      { text: "" },
      { text: "{gain} meters, {times} sessions to date," },
      { text: "and I hate it the way that you love something great." },
      { text: "One day I'll charge up and it won't feel tall." },
      { text: "(Don't tell it, but that day I'll miss it. That's all.)" },
    ],
  },
  {
    id: "hill-beast/the-hills-diary",
    kind: "hill-beast",
    form: "verse",
    band: "any",
    mood: "absurd",
    slots: ["times"],
    lines: [
      { text: "Dear Diary — the hill writes — that kid returned." },
      { text: "Rushed my north face again. Zero lessons learned." },
      { text: "Tried the \"lean forward\" trick. Adorable. Slow." },
      { text: "Made sounds like a kettle. Kept saying, \"Let's GO.\"" },
      { text: "" },
      { text: "That's {times} visits. My record still stands." },
      { text: "But between us? I flatten a bit where it lands." },
      { text: "If it reads this — I'll deny it — but kid, if you knew:" },
      { text: "(hills only keep diaries for one or two.)" },
    ],
  },
  {
    id: "hill-beast/the-gentle-beast",
    kind: "hill-beast",
    form: "verse",
    band: "small",
    mood: "sheepish",
    slots: ["times"],
    lines: [
      { text: "My beast is a gentle one. Modest of height." },
      { text: "Other kids' hills block their half of the light." },
      { text: "Mine's more of a ramp with a serious streak," },
      { text: "the kind of a climb that just seasons the week." },
      { text: "" },
      { text: "But steepness is personal. Effort is too." },
      { text: "A beast is whatever growls uphill at YOU." },
      { text: "So laugh at my ramp, all you mountain-y folk." },
      { text: "({times} climbs. Zero walk-ups. No joke.)" },
    ],
  },
  {
    id: "hill-beast/measured-in-stories",
    kind: "hill-beast",
    form: "verse",
    band: "large",
    mood: "triumphant",
    slots: ["gain", "times"],
    lines: [
      { text: "They measure most hills in meters. Fine, sure." },
      { text: "Mine's measured in stories you tell to endure:" },
      { text: "\"The Time My Face Froze,\" \"The Great Sideways Rain,\"" },
      { text: "\"The Morning My Shadow Refused It\" (fair, shadow. Sane.)" },
      { text: "" },
      { text: "{gain} meters, {times} ascents." },
      { text: "The view from the top is my favorite expense." },
      { text: "The guidebooks rank summits in stars, up to five." },
      { text: "(Mine gets five \"WOOO\"s. And we're both still alive.)" },
    ],
  },
];
