import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "hilliest-run/the-hill-curled-over",
    kind: "hilliest-run",
    form: "verse",
    band: "any",
    mood: "triumphant",
    slots: ["gain"],
    introduces: ["the-hill"],
    lines: [
      { text: "The hill on this run wasn't hilling around." },
      { text: "It went UP like a wall that had quit with the ground." },
      { text: "So steep at the top that it curled like a wave —" },
      { text: "I ran the last bit on the UNDERSIDE. (Brave.)" },
      { text: "" },
      { text: "{gain} meters of climb on the day." },
      { text: "My shoes still walk tilted. My socks slid away." },
      { text: "Was it worth it? The view held the whole town, unfurled." },
      { text: "(Plus, briefly, I hung from the edge of the world.)" },
    ],
  },
  {
    id: "hilliest-run/the-hill-makes-an-offer",
    kind: "hilliest-run",
    form: "verse",
    band: "any",
    mood: "steady",
    slots: [],
    introduces: ["the-hill"],
    lines: [
      { text: "Halfway up, the hill and I had a talk." },
      { text: "The hill offered options: \"You could always walk.\"" },
      { text: "\"Walking's allowed. It's practically free.\"" },
      { text: "\"Lots of nice people walk up me.\"" },
      { text: "" },
      { text: "Hills are good salesmen. The pitch nearly took." },
      { text: "But I shook my head slowly and ran, and it shook —" },
      { text: "the whole hill was laughing. \"You DIDN'T! You DID!\"" },
      { text: "(Respect from a hill is a marvelous thing, kid.)" },
    ],
  },
  {
    id: "hilliest-run/what-goes-up",
    kind: "hilliest-run",
    form: "verse",
    band: "any",
    mood: "triumphant",
    slots: ["gain"],
    lines: [
      { text: "\"What goes up must come down,\" says the saying. All right —" },
      { text: "but the saying leaves out that the UP is a fight," },
      { text: "that the up eats your breakfast, your breath, your knees," },
      { text: "and hands them all back at the top, with the breeze." },
      { text: "" },
      { text: "{gain} meters I paid on the way." },
      { text: "The downhill refunded me — WHEEE — in one pay." },
      { text: "So yes, what goes up comes back down, as they warn." },
      { text: "(But nobody mentions you land back RE-BORN.)" },
    ],
  },
  {
    id: "hilliest-run/permit-and-rope",
    kind: "hilliest-run",
    form: "verse",
    band: "large",
    mood: "triumphant",
    slots: ["gain"],
    lines: [
      { text: "Some hills are bumps. You forgive them. You cope." },
      { text: "This one required a permit and rope." },
      { text: "Birds took a shuttle. The clouds walked the last bit." },
      { text: "{gain} meters. I counted. Then quit." },
      { text: "" },
      { text: "At the top, out of breath, out of legs, out of song," },
      { text: "I stood on the roof where the weather belongs," },
      { text: "looked down at my street, very small, very far:" },
      { text: "(From up here, the town fits inside a jam jar.)" },
    ],
  },
  {
    id: "hilliest-run/the-hillock",
    kind: "hilliest-run",
    form: "verse",
    band: "small",
    mood: "sheepish",
    slots: ["gain"],
    lines: [
      { text: "It wasn't a mountain. Let's start with the truth." },
      { text: "It was more of a... hillock. A slope with a tooth." },
      { text: "But slopes count as climbing! The rule is precise:" },
      { text: "if your calves file a comment, you've paid the full price." },
      { text: "" },
      { text: "{gain} meters — every one real." },
      { text: "Stack them up sideways, that's a big deal." },
      { text: "Mountains get postcards and hikers and fame." },
      { text: "(My hillock got ME. It prefers it that way. No shame.)" },
    ],
  },
  {
    id: "hilliest-run/gravity-pays-up",
    kind: "hilliest-run",
    form: "verse",
    band: "any",
    mood: "absurd",
    slots: ["gain"],
    lines: [
      { text: "Gravity runs a strict pay-as-you-go:" },
      { text: "each meter of up costs a puff or a blow." },
      { text: "I huffed up its hillside, I paid every fee," },
      { text: "{gain} meters, receipts upon me." },
      { text: "" },
      { text: "Then gravity, grumbling, per rules it can't bend," },
      { text: "paid ALL of it back on the downhill, my friend —" },
      { text: "with interest! I flew! My feet barely came down!" },
      { text: "(Gravity hates runners. We bankrupt the town.)" },
    ],
  },
];
