import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "hilliest-run/gravity-took-it-personally",
    kind: "hilliest-run",
    form: "quip",
    band: "any",
    mood: "absurd",
    slots: [],
    lines: [
      { text: "Gravity noticed you were headed up." },
      { text: "Gravity takes that kind of thing to heart." },
      { text: "The whole way down, it held your hand too tight." },
    ],
  },
  {
    id: "hilliest-run/the-hill-pretended",
    kind: "hilliest-run",
    form: "quatrain",
    band: "any",
    mood: "steady",
    slots: [],
    lines: [
      { text: "The hill pretended not to see you coming." },
      { text: "It practiced looking gentle from below." },
      { text: "Halfway up it dropped the whole disguise." },
      { text: "You climbed the honest version to the top." },
    ],
  },
  {
    id: "hilliest-run/speed-bump-with-ambitions",
    kind: "hilliest-run",
    form: "dialogue",
    band: "small",
    mood: "absurd",
    slots: [],
    lines: [
      { text: "You call this a hill? you said, going over it.", voice: 1 },
      { text: "I'm a hill in my heart, the speed bump said.", voice: 2 },
      { text: "You are four inches tall, you pointed out.", voice: 1 },
      { text: "Everest started somewhere, said the bump.", voice: 2 },
      { text: "So did the Alps, it added. So did your knees.", voice: 2 },
      { text: "You gave it that. You let it have that one.", voice: 1 },
    ],
  },
  {
    id: "hilliest-run/notice-a-modest-rise",
    kind: "hilliest-run",
    form: "notice",
    band: "small",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "NOTICE: The ground went up a little bit." },
      { text: "Not enough to brag about. Enough to feel." },
      { text: "Enough that the legs looked up from their work" },
      { text: "and said: oh, we are doing this now, are we." },
      { text: "And did it. That's the whole notice. Well done." },
    ],
  },
  {
    id: "hilliest-run/letter-from-partway-up",
    kind: "hilliest-run",
    form: "letter",
    band: "medium",
    mood: "steady",
    slots: [],
    lines: [
      { text: "Dear runner, from the bend you hoped would be the top:" },
      { text: "" },
      { text: "I'm sorry. I know. There's more of me above." },
      { text: "There is always, a little, more of me above." },
      { text: "But look what you can see from here already —" },
      { text: "the roofs gone small, the whole loop laid out flat." },
      { text: "" },
      { text: "The rest is just the same trick, done again. — the hill" },
    ],
  },
  {
    id: "hilliest-run/receipt-for-the-climb",
    kind: "hilliest-run",
    form: "list",
    band: "medium",
    mood: "steady",
    slots: ["gain"],
    lines: [
      { text: "Itemized, the climb, for your own records:" },
      { text: "{gain} meters of up, none of it refunded;", indent: 1 },
      { text: "one lungful you are never getting back;", indent: 1 },
      { text: "two swears, unprintable, and richly earned;", indent: 1 },
      { text: "the exact dead weight of not turning around;", indent: 1 },
      { text: "and, at the top, the whole sky, on the house.", indent: 1 },
    ],
  },
  {
    id: "hilliest-run/the-long-way-up",
    kind: "hilliest-run",
    form: "concrete",
    band: "large",
    mood: "triumphant",
    slots: [],
    lines: [
      { text: "and", indent: 0 },
      { text: "then", indent: 0 },
      { text: "the", indent: 1 },
      { text: "road", indent: 1 },
      { text: "tilted", indent: 1 },
      { text: "up", indent: 2 },
      { text: "and", indent: 2 },
      { text: "kept", indent: 2 },
      { text: "tilting", indent: 3 },
      { text: "until the sky", indent: 3 },
      { text: "was just more hill", indent: 3 },
      { text: "and you were in it.", indent: 3 },
    ],
  },
  {
    id: "hilliest-run/spell-for-the-last-pitch",
    kind: "hilliest-run",
    form: "spell",
    band: "large",
    mood: "triumphant",
    slots: [],
    lines: [
      { text: "For the last pitch, when the hill turns openly cruel:" },
      { text: "shorten the stride until it's almost nothing." },
      { text: "Almost nothing, done enough times, is a summit." },
      { text: "Do not look up. The top does not need watching;" },
      { text: "it isn't going anywhere. Only you are." },
      { text: "Arrive surprised. It's better that way. Arrive." },
    ],
  },
];
