import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "journey/packed-your-shoes",
    kind: "journey",
    form: "quip",
    band: "any",
    mood: "absurd",
    slots: [],
    lines: [
      { text: "You flew four thousand miles and packed your shoes." },
      { text: "You crossed an ocean to run beside a different sea." },
      { text: "The legs, jet-lagged, did not notice the upgrade." },
    ],
  },
  {
    id: "journey/a-strangers-morning",
    kind: "journey",
    form: "quatrain",
    band: "any",
    mood: "steady",
    slots: ["km"],
    lines: [
      { text: "In a city that cannot pronounce your name," },
      { text: "you ran {km} kilometers of a stranger's morning." },
      { text: "No one knew you. No one knew to wave." },
      { text: "You waved at them regardless. It translated fine." },
    ],
  },
  {
    id: "journey/you-and-the-suitcase",
    kind: "journey",
    form: "dialogue",
    band: "small",
    mood: "absurd",
    slots: [],
    lines: [
      { text: "You packed the shoes again, the suitcase sighed.", voice: 1 },
      { text: "Of course, you said. Where I go, they go.", voice: 2 },
      { text: "We are visiting a wonder of the world, it said.", voice: 1 },
      { text: "And you'll want to jog past it at dawn, I suppose.", voice: 1 },
      { text: "I will, you said, and photograph it out of breath.", voice: 2 },
      { text: "The suitcase, well-traveled, had expected as much.", voice: 1 },
    ],
  },
  {
    id: "journey/customs-declaration",
    kind: "journey",
    form: "notice",
    band: "small",
    mood: "absurd",
    slots: [],
    lines: [
      { text: "CUSTOMS DECLARATION: one pair of shoes, well-used." },
      { text: "Purpose of visit: to run somewhere and leave." },
      { text: "Nothing to declare but a familiar ache abroad." },
      { text: "The officer waved you through. Runners are harmless." },
      { text: "Stamp acquired. The shoes now have a passport too." },
    ],
  },
  {
    id: "journey/places-these-shoes-have-been",
    kind: "journey",
    form: "list",
    band: "medium",
    mood: "steady",
    slots: [],
    lines: [
      { text: "Places these shoes have been that you forget:" },
      { text: "a towpath in the rain, in a borrowed country;", indent: 1 },
      { text: "a hotel hallway, at a shameful hour;", indent: 1 },
      { text: "a hill abroad that did not know your language;", indent: 1 },
      { text: "a beach that stole a little of them, grain by grain;", indent: 1 },
      { text: "and home, always home, still holding all of it.", indent: 1 },
    ],
  },
  {
    id: "journey/one-of-you-was-lovely",
    kind: "journey",
    form: "letter",
    band: "medium",
    mood: "absurd",
    slots: [],
    lines: [
      { text: "To the runner in the gray shoes. Possibly you." },
      { text: "" },
      { text: "Forgive me — I get so many of you tourists." },
      { text: "Were you the one who stopped to photograph the bridge?" },
      { text: "Or the one the pigeons chased? I hope the pigeon one." },
      { text: "You all run like you're late for the same plane." },
      { text: "" },
      { text: "Anyway: one of you was lovely. — a street abroad" },
    ],
  },
  {
    id: "journey/for-a-strange-city",
    kind: "journey",
    form: "spell",
    band: "large",
    mood: "steady",
    slots: [],
    lines: [
      { text: "Step out into a city that owes you nothing." },
      { text: "Turn left by instinct. Get a little lost on purpose." },
      { text: "Let the river, whichever river, be your thread back." },
      { text: "Do not chase the landmarks; run the ordinary streets," },
      { text: "the ones where the city keeps its real face." },
      { text: "Then find your door by the smell of strange bread. Home." },
    ],
  },
  {
    id: "journey/the-long-arc",
    kind: "journey",
    form: "concrete",
    band: "large",
    mood: "absurd",
    slots: [],
    lines: [
      { text: "here", align: "center" },
      { text: "then a long", align: "center" },
      { text: "arcing", align: "center" },
      { text: "line", align: "center" },
      { text: "over the ocean", align: "center" },
      { text: "to there —", align: "center" },
      { text: "and then, absurdly,", align: "center" },
      { text: "a small loop", align: "center" },
      { text: "on foot.", align: "center" },
    ],
  },
];
