import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "journey/the-sneakers-said-us-too",
    kind: "journey",
    form: "verse",
    band: "any",
    mood: "steady",
    slots: ["km"],
    introduces: ["shoes"],
    lines: [
      { text: "The suitcase took socks. It took shirts. It took care." },
      { text: "But the sneakers said, \"US TOO,\" from the top of the stair." },
      { text: "So we flew {km} kilometers, us three —" },
      { text: "me and two shoes with a strong case of WE." },
      { text: "" },
      { text: "New street, new birds, new dogs, new sun." },
      { text: "Same feet, same drumbeat, same morning run." },
      { text: "You can pack up a kid and fly half the world's spin," },
      { text: "(but the run's in the kid. It was already packed in.)" },
    ],
  },
  {
    id: "journey/the-sun-commutes",
    kind: "journey",
    form: "verse",
    band: "any",
    mood: "absurd",
    slots: ["km"],
    lines: [
      { text: "I ran a new city, {km} K from my door." },
      { text: "Different pigeons. New puddles. An un-learned shore." },
      { text: "I braced for the strangeness. I laced up slow..." },
      { text: "then the sun rolled up, calling, \"YOU again? Go!\"" },
      { text: "" },
      { text: "Turns out the sun does this route every day," },
      { text: "commuting the sky in its round-trip way." },
      { text: "Wherever I land, it's already deployed." },
      { text: "(You can't outrun home when the sun's this employed.)" },
    ],
  },
  {
    id: "journey/dogs-bark-in-accents",
    kind: "journey",
    form: "verse",
    band: "any",
    mood: "absurd",
    slots: ["km"],
    lines: [
      { text: "A dog barked at me in a whole other land —" },
      { text: "new fence, new flag, new brand of sand —" },
      { text: "and I don't speak the language, not one single sound," },
      { text: "but I know \"KID, RUN FASTER!\" when I hear it, world-round." },
      { text: "" },
      { text: "{km} kilometers from my own street," },
      { text: "and the message translated: keep moving those feet." },
      { text: "So here's what I learned about \"foreign\" and \"far\":" },
      { text: "(to dogs and to sneakers, you're just who you are.)" },
    ],
  },
  {
    id: "journey/contents-may-settle",
    kind: "journey",
    form: "verse",
    band: "any",
    mood: "sheepish",
    slots: ["km"],
    coda: {
      requires: "shadow",
      lines: [
        { text: "P.S. My shadow flew separately. Fussy old thing." },
        { text: "It met me at sunset, refreshed, by the swing." },
      ],
    },
    lines: [
      { text: "Jet lag is real. My feet thought it was night." },
      { text: "My knees thought it was Tuesday. My lungs weren't right." },
      { text: "The first run abroad is a wobbly affair:" },
      { text: "half of you's HERE and the rest's in the air." },
      { text: "" },
      { text: "By lap two, the parts of me finally synced," },
      { text: "{km} kilometers re-linked." },
      { text: "A body's a suitcase that carries a spark." },
      { text: "(Contents may settle. Just run till they park.)" },
    ],
  },
  {
    id: "journey/pleased-to-meet-you",
    kind: "journey",
    form: "verse",
    band: "small",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "Not every journey's a jumbo-jet ride." },
      { text: "Some are a train and a nap and a stride." },
      { text: "New town, same country, a morning to spare," },
      { text: "so I did what I do when my sneakers are there." },
      { text: "" },
      { text: "A run's how you say to a place, \"Pleased to meet you\" —" },
      { text: "you shake with your feet and the streets kind of greet you." },
      { text: "Tourists take photos. I take the lay of the land." },
      { text: "(My postcards are footprints. Free. And grand.)" },
    ],
  },
  {
    id: "journey/half-the-map",
    kind: "journey",
    form: "verse",
    band: "large",
    mood: "triumphant",
    slots: ["km"],
    lines: [
      { text: "{km} kilometers. HALF THE MAP." },
      { text: "The plane had three dinners, two movies, one nap." },
      { text: "I stepped out the airport, all noodle and yawn," },
      { text: "and the very next morning, I ran on a foreign dawn." },
      { text: "" },
      { text: "The other side of Earth! Where the drains swirl reversed!" },
      { text: "Where my winter is summer! Where dessert can come first!" },
      { text: "And yet when I ran there, the feeling was plain:" },
      { text: "(you can flip the whole planet. The kid stays the same.)" },
    ],
  },
];
