import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "last-run/save-me-a-seat",
    kind: "last-run",
    form: "verse",
    band: "any",
    mood: "quiet",
    slots: [],
    coda: {
      requires: "shadow",
      lines: [
        { text: "P.S. My shadow came too, the whole way." },
        { text: "We're speaking again. (It let ME win today.)" },
      ],
    },
    lines: [
      { text: "We took the long way, me and the street," },
      { text: "the looking-at-everything pace for feet." },
      {
        branch: {
          variants: [
            {
              when: { season: ["winter"] },
              lines: [
                { text: "The mailbox had a snow hat on. I fixed it, twice." },
                { text: "Even the puddles had turned into ice." },
              ],
            },
            {
              when: { season: ["monsoon"] },
              lines: [
                { text: "The rain ran beside me — it needed no shoes." },
                { text: "The gutters were rivers with places to choose." },
              ],
            },
          ],
          default: [
            { text: "The mailbox got a pat. The hill got waved at, twice." },
            { text: "Even the dog at the corner was nice." },
          ],
        },
      },
      { text: "" },
      { text: "\"Same time next year?\" asked the crack in the road." },
      { text: "\"You know me,\" I said. And the streetlight glowed," },
      { text: "and all the way home my sneakers kept beat —" },
      { text: "next year's already out there. (Save me a seat.)" },
    ],
  },
  {
    id: "last-run/the-shoes-wont-retire",
    kind: "last-run",
    form: "verse",
    band: "any",
    mood: "quiet",
    slots: ["km"],
    coda: {
      requires: "shoes",
      lines: [
        { text: "P.S. — yes, the same shoes that trained on their own." },
        { text: "They're not being retired. They're being outgrown." },
      ],
    },
    lines: [
      { text: "The last one measured {km}, door to door." },
      { text: "My shoes came home with less shoe than before:" },
      { text: "the left one whistles gently through its toe," },
      { text: "the right one's sole is waving hi below." },
      { text: "" },
      { text: "They should retire. They can't. They won't." },
      { text: "I reached to bin them — and I don't," },
      { text: "because the left one, soft and low," },
      { text: "whistled the first eight bars of GO." },
    ],
  },
  {
    id: "last-run/dear-next-year",
    kind: "last-run",
    form: "verse",
    band: "any",
    mood: "steady",
    slots: [],
    coda: {
      requires: "the-dog",
      lines: [
        { text: "P.S. The corner dog asked me to add:" },
        { text: "same time, same laughing. (He wasn't so bad.)" },
      ],
    },
    lines: [
      { text: "Dear Next Year — quick, before you start:" },
      { text: "bring hills. I've grown to like the hard part." },
      { text: "Bring rain. I have a hood. Bring cold." },
      { text: "Bring mornings made of dark and gold." },
      { text: "" },
      { text: "Don't change the dog. Don't change the bend" },
      { text: "where the puddle lives. And don't pretend" },
      { text: "you're new. You're just the old year, dressed." },
      { text: "(I liked the old year. Do your best.)" },
    ],
  },
  {
    id: "last-run/collected-on-the-way",
    kind: "last-run",
    form: "list",
    band: "any",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "Collected on the last run of the year:" },
      { text: "one icicle nose (attached, don't fear);", indent: 1 },
      { text: "one pebble, smuggled home in my shoe;", indent: 1 },
      { text: "three dog hellos; a sunset; a view;", indent: 1 },
      { text: "the smell of somebody's dinner (beef stew);", indent: 1 },
      { text: "and every run before this one, too —", indent: 1 },
      { text: "they all ran along at the back, in a line." },
      { text: "(A whole year, carried by two feet. Both mine.)" },
    ],
  },
  {
    id: "last-run/noise-for-the-winter",
    kind: "last-run",
    form: "verse",
    band: "any",
    mood: "nocturnal",
    slots: [],
    coda: {
      requires: "the-quiet",
      lines: [
        { text: "P.S. The Quiet showed up as I got to my door —" },
        { text: "not to take back the street. Just to hear one run more." },
      ],
    },
    lines: [
      { text: "I ran the last one nice and loud —" },
      { text: "big breaths, big steps — I hummed, I bowed," },
      { text: "I smacked the stop sign, slapped the rail," },
      { text: "and left a racket on the trail," },
      { text: "" },
      { text: "because the street will stand out there" },
      { text: "all winter, in the quiet air," },
      { text: "with nothing to listen to. Streets can't sing." },
      { text: "So I left it enough noise to last until spring." },
    ],
  },
  {
    id: "last-run/un-run-the-word-done",
    kind: "last-run",
    form: "verse",
    band: "any",
    mood: "steady",
    slots: ["year"],
    lines: [
      { text: "\"Last run,\" says the calendar. Calendars lie." },
      { text: "They fold up the year and they wave it goodbye," },
      { text: "but feet don't have pages. A run isn't \"done\" —" },
      { text: "it just waits by the door for the next-next one." },
      { text: "" },
      { text: "I'll say it official, so calendars grin:" },
      { text: "THE FINAL RUN, {year}. (Signed.) FIN." },
      { text: "Then I'll lace up tomorrow, first frost or first sun," },
      { text: "and quietly go un-run the word \"done.\"" },
    ],
  },
];
