import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "last-run/the-light-left-burning",
    kind: "last-run",
    form: "quatrain",
    band: "any",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "This was the last one written in the book." },
      { text: "The book, of course, does not believe in last." },
      { text: "It leaves a blank page open, like a lamp," },
      { text: "in case you come back late and need the room." },
    ],
  },
  {
    id: "last-run/the-road-said-see-you",
    kind: "last-run",
    form: "quip",
    band: "any",
    mood: "steady",
    slots: [],
    lines: [
      { text: "The road did not say goodbye. Roads never do." },
      { text: "It said the usual, quieter: see you soon." },
      { text: "It always says soon. It is often, sweetly, wrong." },
    ],
  },
  {
    id: "last-run/notice-the-record-closes",
    kind: "last-run",
    form: "notice",
    band: "any",
    mood: "steady",
    slots: ["km"],
    lines: [
      { text: "NOTICE: The record closes here, at {km} km." },
      { text: "Please note the record is not the running." },
      { text: "The running has no ledger and no last." },
      { text: "It kept happening in shoes we couldn't file." },
      { text: "The Department wishes it could log the rest." },
    ],
  },
  {
    id: "last-run/note-the-shoes-left",
    kind: "last-run",
    form: "letter",
    band: "any",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "Dear feet, a note, left folded in the left shoe:" },
      { text: "" },
      { text: "That was the last of the ones we counted this year." },
      { text: "Don't read too much into a number stopping." },
      { text: "We're by the door. We are always by the door." },
      { text: "The mud is just the year we didn't wash off." },
      { text: "" },
      { text: "Whenever. No rush. We're patient. — the shoes" },
    ],
  },
  {
    id: "last-run/things-it-pretended-not-to-be",
    kind: "last-run",
    form: "list",
    band: "any",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "Things the last run swore it wasn't, all the way home:" },
      { text: "the final one;", indent: 1 },
      { text: "a big deal;", indent: 1 },
      { text: "sad in a way a grown adult would admit to;", indent: 1 },
      { text: "slower than usual on account of stalling;", indent: 1 },
      { text: "reluctant, at the turn, to point back home.", indent: 1 },
    ],
  },
  {
    id: "last-run/one-more-you-said",
    kind: "last-run",
    form: "dialogue",
    band: "any",
    mood: "steady",
    slots: [],
    lines: [
      { text: "One more, you said. There's room for one more yet.", voice: 1 },
      { text: "The year is nearly spent, the calendar said.", voice: 2 },
      { text: "So am I, you said. That's never stopped us once.", voice: 1 },
      { text: "It looked at what was left and did the math.", voice: 2 },
      { text: "Fine. One more, it said. But after that, you rest.", voice: 2 },
      { text: "You ran it slow, on purpose, to make it last.", voice: 1 },
    ],
  },
  {
    id: "last-run/spell-for-after-the-last-one",
    kind: "last-run",
    form: "spell",
    band: "any",
    mood: "steady",
    slots: [],
    lines: [
      { text: "Do not treat the number like a door that locked." },
      { text: "The book is shut; the legs signed nothing at all." },
      { text: "The legs remember. The legs do not read books." },
      { text: "Leave the shoes where light can find them, facing out." },
      { text: "One morning, no reason, they'll be on before you ask." },
      { text: "That morning starts a book nobody's numbered yet." },
    ],
  },
  {
    id: "last-run/the-road-going-on",
    kind: "last-run",
    form: "concrete",
    band: "any",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "the road", indent: 0 },
      { text: "goes on", indent: 1 },
      { text: "past where", indent: 1 },
      { text: "the book", indent: 2 },
      { text: "stops", indent: 2 },
      { text: "counting,", indent: 2 },
      { text: "getting thinner", indent: 3 },
      { text: "and thinner", indent: 3 },
      { text: "but never,", indent: 3 },
      { text: "you'll notice,", indent: 3 },
      { text: "an end.", indent: 3 },
    ],
  },
];
