import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "latest-run/the-moon-was-the-only-witness",
    kind: "latest-run",
    form: "quatrain",
    band: "any",
    mood: "nocturnal",
    slots: [],
    lines: [
      { text: "The clocks had all gone home for the night." },
      { text: "Only the moon still bothered keeping time." },
      { text: "It watched you make your slow loop of the dark" },
      { text: "and told no one, which is the moon's whole job." },
    ],
  },
  {
    id: "latest-run/later-than-the-last-bus",
    kind: "latest-run",
    form: "quip",
    band: "any",
    mood: "nocturnal",
    slots: ["time"],
    lines: [
      { text: "The last bus left at {time} without you." },
      { text: "It wasn't going where you were going anyway." },
      { text: "You were going nowhere, beautifully, on foot." },
    ],
  },
  {
    id: "latest-run/letter-from-the-late-hour",
    kind: "latest-run",
    form: "letter",
    band: "any",
    mood: "nocturnal",
    slots: [],
    lines: [
      { text: "Dear runner, from the far end of the day:" },
      { text: "" },
      { text: "Everyone else has folded up their hours." },
      { text: "The dishes are done. The lights are going out" },
      { text: "one window at a time, the whole street down." },
      { text: "You're still out here, spending what they saved." },
      { text: "" },
      { text: "It's alright. Some days only end this way. — night" },
    ],
  },
  {
    id: "latest-run/notice-after-hours",
    kind: "latest-run",
    form: "notice",
    band: "any",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "NOTICE: You are running well after hours." },
      { text: "The day has closed. Tomorrow isn't open yet." },
      { text: "You are, strictly speaking, between two dates," },
      { text: "out past the edge of when things are allowed." },
      { text: "No one will stop you. No one is even up." },
    ],
  },
  {
    id: "latest-run/things-still-awake-this-late",
    kind: "latest-run",
    form: "list",
    band: "any",
    mood: "nocturnal",
    slots: [],
    lines: [
      { text: "Things still awake this late, and why:" },
      { text: "one fridge, humming, for reasons of its own;", indent: 1 },
      { text: "one traffic light, changing for absolutely no one;", indent: 1 },
      { text: "a moth, employed by the porch bulb next door;", indent: 1 },
      { text: "the stars, who have never once clocked out;", indent: 1 },
      { text: "and you, who could be sleeping, and are not.", indent: 1 },
    ],
  },
  {
    id: "latest-run/you-and-the-late-hour",
    kind: "latest-run",
    form: "dialogue",
    band: "any",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "You know what time it is? the hour inquired.", voice: 1 },
      { text: "I do, you said. That is rather why I'm here.", voice: 2 },
      { text: "Sensible people, it noted, are asleep.", voice: 1 },
      { text: "I'll be sensible tomorrow, you promised it.", voice: 2 },
      { text: "You had no rebuttal. You had, instead, your shoes.", voice: 2 },
      { text: "It had heard that one before. It let you run.", voice: 1 },
    ],
  },
  {
    id: "latest-run/spell-for-the-empty-streets",
    kind: "latest-run",
    form: "spell",
    band: "any",
    mood: "nocturnal",
    slots: [],
    lines: [
      { text: "For the empty streets, so late they feel like yours:" },
      { text: "keep to the light but do not fear the dark." },
      { text: "The dark this late is only the day, resting." },
      { text: "Match your feet to the quiet. Don't outrun it." },
      { text: "Let the town sleep on and never know you passed." },
      { text: "Leave nothing behind but the warmth of having been." },
    ],
  },
  {
    id: "latest-run/one-light-left-on",
    kind: "latest-run",
    form: "concrete",
    band: "any",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "the whole town dark", align: "center" },
      { text: "except", align: "center" },
      { text: "one window", align: "center" },
      { text: "one streetlight", align: "center" },
      { text: "and, under it,", align: "center" },
      { text: "one small", align: "center" },
      { text: "insistent", align: "center" },
      { text: "moving", align: "center" },
      { text: "warmth.", align: "center" },
    ],
  },
];
