import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "latest-run/the-moon-came-along",
    kind: "latest-run",
    form: "verse",
    band: "any",
    mood: "nocturnal",
    slots: ["clock"],
    introduces: ["the-moon"],
    lines: [
      { text: "At {clock} at night, the streets are all yours —" },
      { text: "the daytime is done and rolled up in the stores." },
      { text: "I laced up my shoes on the porch, extra slow." },
      { text: "The moon dropped a notch just to see the show." },
      { text: "" },
      { text: "It followed the whole way. It's not very sly —" },
      { text: "it hid behind rooftops with half of one eye." },
      { text: "I stopped at my door and said, \"Well? Was it fun?\"" },
      { text: "(The moon's now demanding a nightly run.)" },
    ],
  },
  {
    id: "latest-run/officially-bed",
    kind: "latest-run",
    form: "verse",
    band: "any",
    mood: "nocturnal",
    slots: ["clock"],
    lines: [
      { text: "This run is a secret. Officially: bed." },
      { text: "Officially: brushed teeth and dreams in my head." },
      { text: "Unofficially — {clock} — the door had a click," },
      { text: "and the night had a sidewalk, and I had a trick." },
      { text: "" },
      { text: "The dark isn't scary. The dark is just wide." },
      { text: "It fits so much more than the day does inside." },
      { text: "I'll sleep extra hard now. And if I get caught:" },
      { text: "this poem's a story. (It's not. But it ought.)" },
    ],
  },
  {
    id: "latest-run/a-very-patient-cat",
    kind: "latest-run",
    form: "verse",
    band: "any",
    mood: "steady",
    slots: ["clock"],
    lines: [
      { text: "Some days are too full and the run just won't fit —" },
      { text: "you carry it round like a coin in your fist." },
      { text: "School, dinner, the dishes, the this and the that," },
      { text: "and the run waits and waits like a very patient cat." },
      { text: "" },
      { text: "At {clock} — at LAST — the day let me go," },
      { text: "and the run leapt out purring, all stretch and elbow." },
      { text: "Late runs aren't late. Here's the fact they don't teach:" },
      { text: "a run's never late if it's still within reach." },
    ],
  },
  {
    id: "latest-run/streetlight-slalom",
    kind: "latest-run",
    form: "verse",
    band: "any",
    mood: "absurd",
    slots: ["clock"],
    lines: [
      { text: "At night the whole street is a river of dark," },
      { text: "and the streetlights drop circles of light for a lark." },
      { text: "You leap glow to glow — never touch in between!" },
      { text: "(The in-between's water. Or worse: it's unseen.)" },
      { text: "" },
      { text: "At {clock} I crossed the whole river alone," },
      { text: "not one soggy footstep, and hopped my way home." },
      { text: "The rules of this game are the strictest at night." },
      { text: "(I made them. I win them. The scores are all right.)" },
    ],
  },
  {
    id: "latest-run/night-census",
    kind: "latest-run",
    form: "list",
    band: "any",
    mood: "nocturnal",
    slots: ["clock"],
    lines: [
      { text: "Citizens awake at {clock}, a census:" },
      { text: "one owl (on business); two moths (no sense);", indent: 1 },
      { text: "one taxi, empty, singing to itself;", indent: 1 },
      { text: "one cat re-checking every fence and shelf;", indent: 1 },
      { text: "one fridge (mine, later); one entire moon;", indent: 1 },
      { text: "and me, in sneakers, humming my own tune.", indent: 1 },
      { text: "" },
      { text: "Total: not many. And that's the appeal." },
      { text: "(The fewer awake, the more night you can steal.)" },
    ],
  },
  {
    id: "latest-run/note-for-morning-me",
    kind: "latest-run",
    form: "verse",
    band: "any",
    mood: "quiet",
    slots: ["clock"],
    lines: [
      { text: "Morning-me won't believe what the night-me has done." },
      { text: "Morning-me will wake yawning, the sleepiest one." },
      { text: "So I'm leaving a note by the bed, in my shoe:" },
      { text: "\"The {clock} run happened. Signed: you.\"" },
      { text: "" },
      { text: "Because nights disappear like a coin in a well," },
      { text: "and legs remember what mouths never tell," },
      { text: "and when morning-me stretches and wonders why" },
      { text: "the sneakers are warm... there's the note. (That's my guy.)" },
    ],
  },
];
