import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "longest-run/legs-filed-a-complaint",
    kind: "longest-run",
    form: "quip",
    band: "any",
    mood: "absurd",
    slots: [],
    lines: [
      { text: "Your legs filed a complaint with management." },
      { text: "Management, it turns out, is also your legs." },
      { text: "The meeting ran long. So, memorably, did you." },
    ],
  },
  {
    id: "longest-run/horizon-kept-moving",
    kind: "longest-run",
    form: "quatrain",
    band: "any",
    mood: "steady",
    slots: [],
    lines: [
      { text: "You aimed for the far thing and it moved." },
      { text: "You aimed again. Again it slid away." },
      { text: "That is not the horizon being cruel —" },
      { text: "that's only how much far you turned out to have." },
    ],
  },
  {
    id: "longest-run/mailbox-is-proud",
    kind: "longest-run",
    form: "notice",
    band: "small",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "NOTICE from the Mailbox at the End of the Block:" },
      { text: "You made it all the way out here. On foot." },
      { text: "This is, frankly, the farthest anyone has come" },
      { text: "purely to turn around and head straight home." },
      { text: "The mailbox is proud. The mailbox is easily proud." },
    ],
  },
  {
    id: "longest-run/is-that-all",
    kind: "longest-run",
    form: "dialogue",
    band: "small",
    mood: "steady",
    slots: [],
    lines: [
      { text: "Is that the whole run? you asked, a little smug.", voice: 1 },
      { text: "For now, said the distance. For a first draft.", voice: 2 },
      { text: "It felt long, you said. It felt like a whole lot.", voice: 1 },
      { text: "It was a lot, the distance agreed, and kindly.", voice: 2 },
      { text: "Everything is a lot the first time it is far.", voice: 2 },
      { text: "Then it walked you back by the shorter way.", voice: 1 },
    ],
  },
  {
    id: "longest-run/note-from-the-far-mile",
    kind: "longest-run",
    form: "letter",
    band: "medium",
    mood: "steady",
    slots: [],
    lines: [
      { text: "Dear runner, from the mile you don't run often:" },
      { text: "" },
      { text: "I get so few visitors this far out of town." },
      { text: "The pavement here is shy. It doesn't shine." },
      { text: "But you came, and stayed, and hardly checked the time" },
      { text: "more than you had to. I noticed. I keep count." },
      { text: "" },
      { text: "Come back when the long mood takes you. — the far mile" },
    ],
  },
  {
    id: "longest-run/spell-for-the-middle-miles",
    kind: "longest-run",
    form: "spell",
    band: "medium",
    mood: "steady",
    slots: [],
    lines: [
      { text: "For the middle miles, where the shine wears off:" },
      { text: "do not count what is left. Count what still holds." },
      { text: "The lungs are holding. Good. The knees, complaining —" },
      { text: "complaining is a kind of holding on as well." },
      { text: "Fix your eyes one mailbox further down the road." },
      { text: "Arrive. Then pick the next. That is the whole trick." },
    ],
  },
  {
    id: "longest-run/what-the-road-collected",
    kind: "longest-run",
    form: "list",
    band: "large",
    mood: "triumphant",
    slots: ["km"],
    lines: [
      { text: "Things the road collected on the day you wouldn't stop:" },
      { text: "one sunrise, slightly used;", indent: 1 },
      { text: "a dog's opinion, freely given;", indent: 1 },
      { text: "the neighborhood's whole supply of hills;", indent: 1 },
      { text: "four kinds of weather, three of them at once;", indent: 1 },
      { text: "and every single one of your excuses", indent: 1 },
      { text: "(it keeps them in a jar).", indent: 1 },
      { text: "" },
      { text: "Then it wrote {km} kilometers in the ledger," },
      { text: "and stamped it PAID IN FULL —" },
      { text: "the road does not do refunds." },
    ],
  },
  {
    id: "longest-run/what-the-shadow-saw",
    kind: "longest-run",
    form: "narrative",
    band: "large",
    mood: "triumphant",
    slots: [],
    lines: [
      { text: "The shadow had planned an ordinary day." },
      { text: "A little stretch of morning, then some shade," },
      { text: "a nap beneath a bench at around eleven," },
      { text: "the usual short loop, and home in time for lunch." },
      { text: "Instead you turned left where you always turn back." },
      { text: "The shadow, startled, lengthened to keep up." },
      { text: "Past the school. Past the water tower. Past" },
      { text: "the point where roads stop bothering with sidewalks." },
      { text: "It quit complaining somewhere near the river." },
      { text: "It started, quietly, to keep you company." },
      { text: "By the far turn it had given up on lunch." },
      { text: "By the last hill it had given up on doubt." },
      { text: "And when you finally, finally slowed to a walk," },
      { text: "the shadow did not race ahead to rest." },
      { text: "It stayed exactly your size, and matched your breath," },
      { text: "and went the whole way home a step behind." },
    ],
  },
];
