import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "longest-run/the-hero-and-the-car",
    kind: "longest-run",
    form: "verse",
    band: "any",
    mood: "triumphant",
    slots: ["km"],
    introduces: ["the-mailbox"],
    lines: [
      { text: "I ran past the mailbox, I ran past the school," },
      { text: "I ran past the sign that says DON'T RUN (a rule)," },
      { text: "I ran out of sidewalk, I ran out of street," },
      { text: "I ran out of everything — except for feet." },
      { text: "" },
      { text: "{km} kilometers! I finished! I win!" },
      { text: "The town ought to carve me in bronze, or in tin." },
      { text: "How did your hero get home from so far?" },
      { text: "...The hero would rather not talk about the car." },
    ],
  },
  {
    id: "longest-run/the-silent-treatment",
    kind: "longest-run",
    form: "verse",
    band: "any",
    mood: "absurd",
    slots: ["km"],
    lines: [
      { text: "My left leg said, \"I quit at eight.\"" },
      { text: "My right leg said, \"Let's renegotiate.\"" },
      { text: "My knees proposed a general strike." },
      { text: "My feet said, \"Fine! Go buy a bike!\"" },
      { text: "" },
      { text: "The argument got loud and long." },
      { text: "Meanwhile — funny — we ran on." },
      { text: "{km} kilometers, door to door." },
      { text: "(Nobody's speaking anymore.)" },
    ],
  },
  {
    id: "longest-run/advice-from-the-far-end",
    kind: "longest-run",
    form: "verse",
    band: "large",
    mood: "sheepish",
    slots: ["km"],
    lines: [
      { text: "A word of advice from the far end of town," },
      {
        branch: {
          variants: [
            {
              when: { hourBand: ["evening", "night"] },
              lines: [{ text: "where the sidewalk gives up and the sun's going down:" }],
            },
          ],
          default: [{ text: "where the sidewalk gives up and the houses calm down:" }],
        },
      },
      { text: "when you run out {km} — you brave little dot —" },
      { text: "the run home is exactly as long. I forgot." },
    ],
  },
  {
    id: "longest-run/the-corner-dog-bet-low",
    kind: "longest-run",
    form: "verse",
    band: "any",
    mood: "steady",
    slots: ["km"],
    introduces: ["the-dog"],
    lines: [
      { text: "The corner dog came along to laugh." },
      { text: "He gave me a block — okay, a block and a half." },
      { text: "By the end of it, though, he'd stopped laughing to pant." },
      { text: "A little bit later he sat by a plant." },
      { text: "" },
      { text: "I ran on alone, {km} in all," },
      { text: "then passed him again coming home, standing tall." },
      { text: "He walked me the last little bit to my door," },
      { text: "pretending he'd only been resting before." },
    ],
  },
  {
    id: "longest-run/past-the-park",
    kind: "longest-run",
    form: "verse",
    band: "any",
    mood: "absurd",
    slots: ["weekday"],
    lines: [
      { text: "{weekday}'s run went past the park." },
      { text: "Past the park is where my map goes dark:" },
      { text: "I'd drawn sea serpents there, and doom," },
      { text: "because I'd needed to fill the room." },
      { text: "" },
      { text: "Well. I have now been past the park." },
      { text: "Report: no serpents. One small dog. (It barked.)" },
      { text: "The doom turned out to be a hill." },
      { text: "The dragons... okay, the dragons are there still." },
    ],
  },
  {
    id: "longest-run/one-more-lamppost",
    kind: "longest-run",
    form: "verse",
    band: "any",
    mood: "steady",
    slots: ["weekday"],
    lines: [
      { text: "\"Just one more lamppost,\" I told my feet." },
      { text: "Twelve lampposts later we ran out of street." },
      { text: "\"Just one more corner.\" We turned twenty-two." },
      { text: "My feet don't believe a word I say. (True.)" },
      { text: "" },
      { text: "That's the whole secret to running this far:" },
      { text: "lie to your feet about where your feet are." },
      { text: "They know. They just like where the little lies lead." },
      { text: "(We're all going out again next {weekday}. Agreed.)" },
    ],
  },
];
