import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "month/a-box-you-overfilled",
    kind: "month",
    form: "quip",
    band: "any",
    mood: "absurd",
    slots: ["month"],
    lines: [
      { text: "{month} was a box, and you kept putting runs in it." },
      { text: "By the end it would not close. You sat on the lid." },
      { text: "Some months you fill. This one you overfilled." },
    ],
  },
  {
    id: "month/thirty-little-doors",
    kind: "month",
    form: "quatrain",
    band: "any",
    mood: "steady",
    slots: ["month", "km"],
    lines: [
      { text: "A month is only thirty-ish little doors." },
      { text: "You opened each and left a mile inside." },
      { text: "By {month}'s last day the total came to {km}," },
      { text: "which the month carried out like a full tray." },
    ],
  },
  {
    id: "month/only-thirty-days",
    kind: "month",
    form: "dialogue",
    band: "small",
    mood: "absurd",
    slots: [],
    lines: [
      { text: "Slow down, said the month. I only have thirty days.", voice: 1 },
      { text: "Then I'll use all thirty, you said, and did.", voice: 2 },
      { text: "You're wearing me out, it complained, near the end.", voice: 1 },
      { text: "You wore me out first, you said, which was fair.", voice: 2 },
      { text: "The month conceded, being nearly over anyway,", voice: 1 },
      { text: "and handed you the next one, rested, thirty-one strong.", voice: 1 },
    ],
  },
  {
    id: "month/final-report",
    kind: "month",
    form: "notice",
    band: "small",
    mood: "absurd",
    slots: ["month", "km"],
    lines: [
      { text: "FINAL REPORT for the month of {month}:" },
      { text: "Distance filed: {km} kilometers, give or take a hill." },
      { text: "Mornings spent: several. Excuses spent: fewer." },
      { text: "The month rolls up its calendar and steps aside." },
      { text: "Filed under: done, and quietly proud of you." },
    ],
  },
  {
    id: "month/what-it-was-holding",
    kind: "month",
    form: "list",
    band: "medium",
    mood: "steady",
    slots: ["month"],
    lines: [
      { text: "Everything {month} turned out to be holding:" },
      { text: "a cold snap that arrived without knocking;", indent: 1 },
      { text: "two long runs and a great many short ones;", indent: 1 },
      { text: "a morning so bright it felt like a reward;", indent: 1 },
      { text: "one day off, spent guiltily and well;", indent: 1 },
      { text: "and the quiet click of the month filling up.", indent: 1 },
    ],
  },
  {
    id: "month/writing-on-its-way-out",
    kind: "month",
    form: "letter",
    band: "medium",
    mood: "quiet",
    slots: ["month"],
    lines: [
      { text: "This is {month}, writing on its way out." },
      { text: "" },
      { text: "We had a good run of it, you and I. Thirty days." },
      { text: "You showed up more than you didn't. I noticed." },
      { text: "I am not a long time. I am only a little while." },
      { text: "But you filled me honestly, and that is enough." },
      { text: "" },
      { text: "Yours, and then October's — {month}" },
    ],
  },
  {
    id: "month/take-it-like-a-shelf",
    kind: "month",
    form: "spell",
    band: "large",
    mood: "steady",
    slots: ["month"],
    lines: [
      { text: "Take {month} like a shelf: one thing at a time." },
      { text: "Do not rush to fill it; the days will do that." },
      { text: "Put a run on Monday. The others will gather round it." },
      { text: "Some slots stay empty. That is what months are for." },
      { text: "When it is full, do not weigh it. Just set it down." },
      { text: "Then reach up, honestly, for the next clean one." },
    ],
  },
  {
    id: "month/the-filling-grid",
    kind: "month",
    form: "concrete",
    band: "large",
    mood: "absurd",
    slots: [],
    lines: [
      { text: "thirty squares", align: "center" },
      { text: "cold and blank", align: "center" },
      { text: "then a mark", align: "center" },
      { text: "then another", align: "center" },
      { text: "then a scatter of them", align: "center" },
      { text: "filling the empty", align: "center" },
      { text: "week by week", align: "center" },
      { text: "until the month", align: "center" },
      { text: "is a thing you did.", align: "center" },
    ],
  },
];
