import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "month/fed-it-well",
    kind: "month",
    form: "verse",
    band: "any",
    mood: "absurd",
    slots: ["month", "km"],
    lines: [
      { text: "{month} came hungry, like months do," },
      { text: "with thirty-odd mornings to chew and to chew." },
      { text: "I fed it my sneakers' entire supply:" },
      { text: "{km} kilometers. (Gulp.) \"More pie?\"" },
      { text: "" },
      { text: "Most months just eat calendars, pages, and weeks." },
      { text: "Mine ate a distance with actual peaks." },
      { text: "Now it naps in the archive, too stuffed to be neat," },
      { text: "the fattest month ever measured in feet." },
    ],
  },
  {
    id: "month/what-stays",
    kind: "month",
    form: "verse",
    band: "any",
    mood: "steady",
    slots: ["month", "km"],
    coda: {
      requires: "the-mailbox",
      lines: [
        { text: "P.S. The mailbox has watched me go by every day." },
        { text: "It calls me \"the weather.\" (I'll take it. Hooray.)" },
      ],
    },
    lines: [
      { text: "{month} ended. They always do." },
      { text: "(Which is rude, when you're just getting through.)" },
      { text: "It weighed every run on its way out the door:" },
      { text: "{km} kilometers — did I mention the score?" },
      { text: "" },
      { text: "Months leave and they take all their weather along," },
      { text: "their light and their leaves and their birds and their song." },
      { text: "But guess what stays put, un-took, mine, and immense?" },
      { text: "The legs {month} built. (Present tense.)" },
    ],
  },
  {
    id: "month/the-months-mood",
    kind: "month",
    form: "verse",
    band: "any",
    mood: "steady",
    slots: ["month", "km"],
    lines: [
      { text: "Every month has a mood when you meet it outside." },
      { text: "You don't pick the mood. But you do pick the stride." },
      { text: "" },
      {
        branch: {
          variants: [
            {
              when: { season: ["monsoon"] },
              lines: [
                { text: "{month} chose WATER — the sky as a sea." },
                { text: "I ran like a fish with a place to be." },
              ],
            },
            {
              when: { season: ["winter"] },
              lines: [
                { text: "{month} chose ICE, and a wind with a bite." },
                { text: "I ran wrapped in everything. Ran anyway. (Spite.)" },
              ],
            },
            {
              when: { season: ["summer"] },
              lines: [
                { text: "{month} chose FURNACE. The sidewalk could bake." },
                { text: "I ran before sunup, for goodness's sake." },
              ],
            },
            {
              when: { season: ["autumn"] },
              lines: [
                { text: "{month} chose CONFETTI — the trees throwing leaves." },
                { text: "I ran my parades through it, waving both sleeves." },
              ],
            },
            {
              when: { season: ["spring"] },
              lines: [
                { text: "{month} chose PUDDLES and one bragging bird." },
                { text: "I ran while it sang. Every showoff word." },
              ],
            },
          ],
          default: [
            { text: "{month} kept it simple: gray, breathable, kind." },
            { text: "The best running weather is weather you don't mind." },
          ],
        },
      },
      { text: "" },
      { text: "{km} kilometers, mood and all." },
      { text: "That's the trick with months, both the big and the small:" },
      { text: "you can't choose the weather. The weather's the fee." },
      { text: "(The running's the thing that it buys. And it's free.)" },
    ],
  },
  {
    id: "month/behind-its-doors",
    kind: "month",
    form: "list",
    band: "any",
    mood: "quiet",
    slots: ["month", "km"],
    lines: [
      { text: "What {month} kept behind its doors:" },
      { text: "one run that felt like flying (encore!);", indent: 1 },
      { text: "two runs of the trudging-and-muttering kind;", indent: 1 },
      { text: "one sunrise that stopped me. (I didn't mind.);", indent: 1 },
      { text: "one dog promoted from barker to guard;", indent: 1 },
      { text: "one puddle, ambitious, the size of a yard;", indent: 1 },
      { text: "" },
      { text: "{km} kilometers, door after door," },
      { text: "and I know what's behind them. (Want more? Run more.)" },
    ],
  },
  {
    id: "month/the-modest-month",
    kind: "month",
    form: "verse",
    band: "small",
    mood: "quiet",
    slots: ["month"],
    lines: [
      { text: "{month} was modest. No records, no roar." },
      { text: "Some runs and some rest days. A month, nothing more." },
      { text: "It won't make the highlight reel. Never gets cheers." },
      { text: "It's the month between months that just... quietly steers." },
      { text: "" },
      { text: "But ask any bridge what the secret is: spans." },
      { text: "Ask winter supplies about cans." },
      { text: "The flashy months rest on the modest months' backs." },
      { text: "({month} knows. It carried. Relax.)" },
    ],
  },
  {
    id: "month/check-on-the-sidewalk",
    kind: "month",
    form: "verse",
    band: "large",
    mood: "triumphant",
    slots: ["month", "km"],
    lines: [
      { text: "{month} should be looked at by science." },
      { text: "It broke every meter in gentle defiance." },
      { text: "{km} kilometers. Read it again." },
      { text: "The town's out of sidewalk. The dog's out of zen." },
      { text: "" },
      { text: "They'll study my sneakers. They'll graph every street." },
      { text: "They'll ask, \"How'd this happen?\" I'll shrug: \"I've got feet," },
      { text: "and mornings kept coming, so I kept on spending 'em.\"" },
      { text: "(Science writes: \"Subject just... ran.\" — addendum.)" },
    ],
  },
];
