import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "night-runs/on-the-guest-list",
    kind: "night-runs",
    form: "verse",
    band: "any",
    mood: "nocturnal",
    slots: ["count"],
    lines: [
      { text: "{count} night runs this year. {count} nights" },
      { text: "of streets gone soft under buttery lights." },
      { text: "The first one felt stolen. The second felt sly." },
      { text: "By the last one, the dark just waved me by." },
      { text: "" },
      { text: "The dark keeps a guest list. I'm on it. In pen." },
      { text: "Under \"frequent,\" it says: \"That kid. Again.\"" },
    ],
  },
  {
    id: "night-runs/what-runs-with-me",
    kind: "night-runs",
    form: "verse",
    band: "any",
    mood: "nocturnal",
    slots: ["name"],
    lines: [
      { text: "Something runs with me when I run at night." },
      { text: "It's not the dog. Dogs sleep. It's not the light." },
      { text: "It keeps to the hedges. It matches my pace." },
      { text: "It's never quite there when I turn my face." },
      { text: "" },
      { text: "I asked it one midnight, \"What's your name, friend?\"" },
      { text: "{name},", align: "center" },
      { text: "it breathed, from the hedge at the very block's end." },
      { text: "" },
      { text: "We run as a team now. We own the whole night." },
      { text: "(It's friendly. It's probably friendly. Sleep tight.)" },
    ],
  },
  {
    id: "night-runs/the-dark-door",
    kind: "night-runs",
    form: "verse",
    band: "any",
    mood: "steady",
    slots: ["count"],
    lines: [
      { text: "Daytime running is public. You wave." },
      { text: "You dodge all the strollers. You mind and behave." },
      { text: "But nighttime running is running UNBOUND:" },
      { text: "no audience, no traffic, just you and the sound" },
      { text: "of two quiet sneakers applauding the ground." },
      { text: "" },
      { text: "{count} times I chose the dark door." },
      { text: "(The day thinks I'm lazy. The night knows the score.)" },
    ],
  },
  {
    id: "night-runs/the-moon-arranges-things",
    kind: "night-runs",
    form: "verse",
    band: "any",
    mood: "absurd",
    slots: ["count"],
    coda: {
      requires: "the-moon",
      lines: [
        { text: "P.S. Yes — the same moon that runs with me late." },
        { text: "It told me it's training. (The moon's lost no weight.)" },
      ],
    },
    lines: [
      { text: "The moon doesn't rise for just anyone's sake." },
      { text: "It's got craters to polish and tides to make." },
      { text: "But {count} nights, it arranged to appear" },
      { text: "right over my shoulder. Coincidence? Here?" },
      { text: "" },
      { text: "I checked with the owls, and the owls concur:" },
      { text: "the moon adjusts orbit for kids who prefer" },
      { text: "to run in the dark. It's in charts. It's in ink." },
      { text: "(The moon also spies for my mother. I think.)" },
    ],
  },
  {
    id: "night-runs/once-or-twice",
    kind: "night-runs",
    form: "verse",
    band: "small",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "Twice, maybe once, I ran under the stars." },
      { text: "No streak of the night owl. No moonlit memoirs." },
      { text: "Just once (or twice), when the day came up short," },
      { text: "I borrowed the night as a running resort." },
      { text: "" },
      { text: "But here's what I learned in that one darkened mile:" },
      { text: "the night's been out there the whole entire while," },
      { text: "with spare quiet streets it will lend on request." },
      { text: "(Now I know where they keep it. Don't tell the rest.)" },
    ],
  },
  {
    id: "night-runs/raccoon-hours",
    kind: "night-runs",
    form: "verse",
    band: "any",
    mood: "nocturnal",
    slots: ["clock"],
    lines: [
      { text: "The latest I've run? {clock}. That's late." },
      { text: "The kind of late even raccoons debate." },
      { text: "The town was so quiet, my steps sounded twice —" },
      { text: "an echo per foot, which was actually nice." },
      { text: "" },
      { text: "Somewhere a clock cleared its throat toward day." },
      { text: "The night put a paw on my shoulder: \"...stay.\"" },
      { text: "I didn't. I'm brave, but I'm not a fool:" },
      { text: "(the night gets you home before morning. House rule.)" },
    ],
  },
];
