import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "night-runs/the-moon-comes-along",
    kind: "night-runs",
    form: "quip",
    band: "any",
    mood: "nocturnal",
    slots: [],
    lines: [
      { text: "The moon never asks you where you're going." },
      { text: "It just comes along, the way the good dogs do —" },
      { text: "roof to roof to roof, matching your pace." },
    ],
  },
  {
    id: "night-runs/the-dark-made-room",
    kind: "night-runs",
    form: "quatrain",
    band: "any",
    mood: "nocturnal",
    slots: [],
    lines: [
      { text: "The dark is not as empty as they say." },
      { text: "It's mostly full of people staying in." },
      { text: "You were the one small motion in it, moving," },
      { text: "and the dark, to its own surprise, made room." },
    ],
  },
  {
    id: "night-runs/notice-nocturnal-activity",
    kind: "night-runs",
    form: "notice",
    band: "small",
    mood: "nocturnal",
    slots: ["count"],
    lines: [
      { text: "NOTICE: {count} runs were logged after dark." },
      { text: "The daytime has not been informed of this." },
      { text: "As far as the sun knows, you were fast asleep" },
      { text: "like a reasonable person, in a bed." },
      { text: "Your secret is safe. The streetlights do not talk." },
    ],
  },
  {
    id: "night-runs/you-and-the-porch-light",
    kind: "night-runs",
    form: "dialogue",
    band: "small",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "Out again? the porch light buzzed, half awake.", voice: 1 },
      { text: "Just a short one, you said, tightening a lace.", voice: 2 },
      { text: "That's what you said on Tuesday, it replied.", voice: 1 },
      { text: "This is Tuesday, you said. It let that one go.", voice: 2 },
      { text: "I know, you said, and could not say quite why.", voice: 2 },
      { text: "I'll stay on, it said. For whenever you get back.", voice: 1 },
    ],
  },
  {
    id: "night-runs/letter-from-the-night-shift",
    kind: "night-runs",
    form: "letter",
    band: "medium",
    mood: "nocturnal",
    slots: ["count"],
    lines: [
      { text: "Dear daytime runner, from your midnight half:" },
      { text: "" },
      { text: "We've met {count} times now, though you never say." },
      { text: "You get the mornings. I get the empty roads," },
      { text: "the cold that means it, the streetlights all to us." },
      { text: "I do not mind the trade. I have come to like it." },
      { text: "" },
      { text: "Wake me whenever the day gets too crowded. — you" },
    ],
  },
  {
    id: "night-runs/what-the-night-is-made-of",
    kind: "night-runs",
    form: "list",
    band: "medium",
    mood: "nocturnal",
    slots: [],
    lines: [
      { text: "The night, taken apart and counted out:" },
      { text: "one moon, on loan, returnable by dawn;", indent: 1 },
      { text: "a dog two yards over, entirely off the clock;", indent: 1 },
      { text: "the hum the streetlights make when no one's near;", indent: 1 },
      { text: "your breath, going visible, and then not;", indent: 1 },
      { text: "and all the miles that no one will believe.", indent: 1 },
    ],
  },
  {
    id: "night-runs/spell-for-the-hour-with-no-name",
    kind: "night-runs",
    form: "spell",
    band: "large",
    mood: "nocturnal",
    slots: [],
    lines: [
      { text: "For the hour with no name, past late, before early:" },
      { text: "move quietly. The houses are all dreaming." },
      { text: "Do not wake the dogs; they will want to come." },
      { text: "Run the middle of the road. It's yours tonight." },
      { text: "The city built all this and left it out for you." },
      { text: "Say thanks to the dark. Then use it. Then go." },
    ],
  },
  {
    id: "night-runs/pools-of-light",
    kind: "night-runs",
    form: "concrete",
    band: "large",
    mood: "nocturnal",
    slots: [],
    lines: [
      { text: "light", align: "center" },
      { text: "then dark", align: "center" },
      { text: "then light", align: "center" },
      { text: "then a longer dark", align: "center" },
      { text: "then, far off, light —", align: "center" },
      { text: "and you, going", align: "center" },
      { text: "island to island", align: "center" },
      { text: "across the whole", align: "center" },
      { text: "sleeping town.", align: "center" },
    ],
  },
];
