import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "quiet/the-silence-earned-a-name",
    kind: "quiet",
    form: "quip",
    band: "any",
    mood: "quiet",
    slots: ["days", "name"],
    lines: [
      { text: "After {days} days, the silence earned a name." },
      { text: "You call it {name}" },
      { text: "which is how you make a monster into a guest." },
    ],
  },
  {
    id: "quiet/the-story-is-resting",
    kind: "quiet",
    form: "quatrain",
    band: "any",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "The quiet is not empty; it is full." },
      { text: "It holds the shoes, the door, the good intention." },
      { text: "It is a bookmark in a book laid gently down —" },
      { text: "the story is not over. It is resting." },
    ],
  },
  {
    id: "quiet/it-kept-your-place",
    kind: "quiet",
    form: "dialogue",
    band: "small",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "You're back, said the quiet. I kept your place.", voice: 1 },
      { text: "You kept it too well, you said. I could not move.", voice: 2 },
      { text: "That was not me, it said. That was the rest.", voice: 1 },
      { text: "I only sat with you. I am good at sitting.", voice: 1 },
      { text: "I know, you said. That was the trouble with you.", voice: 2 },
      { text: "Walk with me instead, you said. It tried. It learned.", voice: 2 },
    ],
  },
  {
    id: "quiet/missing-one-runner",
    kind: "quiet",
    form: "notice",
    band: "small",
    mood: "absurd",
    slots: ["days"],
    lines: [
      { text: "MISSING: one runner, last seen {days} days ago." },
      { text: "Answers to the sound of a zipper, or good weather." },
      { text: "Last known to own a pair of shoes, still waiting." },
      { text: "No reward. The shoes will simply be glad." },
      { text: "If found, point gently toward the door." },
    ],
  },
  {
    id: "quiet/what-the-quiet-kept",
    kind: "quiet",
    form: "list",
    band: "medium",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "What the quiet kept while you were gone:" },
      { text: "the shape of you, pressed into the couch;", indent: 1 },
      { text: "one resolution, folded very small;", indent: 1 },
      { text: "the shoes, in their patient, dog-like way;", indent: 1 },
      { text: "a Tuesday you had promised things to;", indent: 1 },
      { text: "and the door, still willing, still unlocked.", indent: 1 },
    ],
  },
  {
    id: "quiet/spell-for-coming-back",
    kind: "quiet",
    form: "spell",
    band: "medium",
    mood: "steady",
    slots: ["name"],
    lines: [
      { text: "When the quiet has a name, it can be answered." },
      { text: "Do not fight it; you can only open the door." },
      { text: "I have come back, {name}." },
      { text: "The spell ends there. It was never a long one." },
      { text: "Coming back is small. Coming back is also everything." },
      { text: "The shoes forgive the wait. Begin. They are ready." },
    ],
  },
  {
    id: "quiet/letter-from-the-shoes",
    kind: "quiet",
    form: "letter",
    band: "large",
    mood: "quiet",
    slots: ["days", "name"],
    lines: [
      { text: "Dear Owner," },
      { text: "" },
      { text: "It has been {days} days. We are still by the door." },
      { text: "The laces have gone stiff from all the waiting." },
      { text: "A spider moved into the left one Tuesday." },
      { text: "We told her you'd be back. She laughed." },
      { text: "" },
      { text: "We are not angry. Shoes are built for patience." },
      { text: "But {name} waits with us," },
      { text: "and it is getting large." },
      { text: "" },
      { text: "Yours truly,", align: "right" },
      { text: "The Shoes", align: "right" },
    ],
  },
  {
    id: "quiet/the-name-grows-large",
    kind: "quiet",
    form: "concrete",
    band: "large",
    mood: "quiet",
    slots: ["name"],
    lines: [
      { text: "it starts small", align: "center" },
      { text: "a hush", align: "center" },
      { text: "a skipped day", align: "center" },
      { text: "then a week of them", align: "center" },
      { text: "then it has a name:", align: "center" },
      { text: "{name}", align: "center" },
      { text: "filling the hallway,", align: "center" },
      { text: "sleeping on the stairs,", align: "center" },
      { text: "wearing your slippers.", align: "center" },
    ],
  },
];
