import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "quiet/the-shoes-kept-training",
    kind: "quiet",
    form: "verse",
    band: "any",
    mood: "absurd",
    slots: ["days"],
    introduces: ["shoes"],
    lines: [
      { text: "For {days} days, my shoes stayed home," },
      { text: "parked by the door like two dogs by a bone." },
      { text: "They practiced their laces. They practiced their squeak." },
      { text: "They ran in their sleep twenty miles a week." },
      { text: "" },
      { text: "But when I came back and I laced them up tight," },
      { text: "they shot off like rockets and ran me all night —" },
      { text: "{days} days of training, that's why." },
      { text: "The shoes are the runner now. I'm just the guy." },
    ],
  },
  {
    id: "quiet/moved-in-rent-free",
    kind: "quiet",
    form: "verse",
    band: "any",
    mood: "nocturnal",
    slots: ["days"],
    introduces: ["the-quiet"],
    lines: [
      { text: "While I was gone, someone moved onto my street:" },
      { text: "no van, no boxes, no knocking, no feet." },
      { text: "It borrowed my bench. It stretched out on my hill." },
      { text: "It padded the potholes. It made the dogs still." },
      { text: "" },
      { text: "{days} days it squatted, rent-free." },
      { text: "It might have stayed years — but then, footsteps! (Me.)" },
      { text: "It didn't move out. It just made itself thin." },
      { text: "It waits by the bench for me to quit again." },
    ],
  },
  {
    id: "quiet/naming-the-beast",
    kind: "quiet",
    form: "verse",
    band: "any",
    mood: "steady",
    slots: ["name", "days"],
    introduces: ["the-quiet"],
    lines: [
      { text: "Every long silence deserves its own name," },
      { text: "like storms do, like ships do. This one became:" },
      { text: "{name}.", align: "center" },
      { text: "Say it out loud. Feel the weight of the blame." },
      { text: "" },
      { text: "It measured {days} days, end to end." },
      { text: "It swallowed my sneakers. It bored my best friend." },
      { text: "But naming a thing makes it yours — that's the art." },
      { text: "It's mine now. It sits. It rolls over. (Smart.)" },
    ],
  },
  {
    id: "quiet/official-excuses",
    kind: "quiet",
    form: "list",
    band: "any",
    mood: "sheepish",
    slots: ["days"],
    lines: [
      { text: "Official excuses, in order of use:" },
      { text: "The weather (too weathery). Shoes (too loose).", indent: 1 },
      { text: "Busy. SO busy. The busiest kid.", indent: 1 },
      { text: "A knee did a thing. (No it didn't.) (It did.)", indent: 1 },
      { text: "October. November. The general gloom.", indent: 1 },
      { text: "The sidewalk was rude to me. Also: no room.", indent: 1 },
      { text: "" },
      { text: "{days} days, that pile grew tall." },
      { text: "Then one plain morning — no reason at all —" },
      { text: "I ran. And the pile? It's still by the door." },
      { text: "(Excuses keep fine. I may need them once more.)" },
    ],
  },
  {
    id: "quiet/the-streetlight-log",
    kind: "quiet",
    form: "verse",
    band: "any",
    mood: "nocturnal",
    slots: ["days"],
    coda: {
      requires: "shadow",
      lines: [
        { text: "P.S. My shadow just smirked when I glared its way." },
        { text: "(It taught streetlights sarcasm while I was away.)" },
      ],
    },
    lines: [
      { text: "The streetlight keeps a little log" },
      { text: "of every runner, every dog." },
      { text: "For {days} days, its page for me" },
      { text: "was blank as blank as blank can be." },
      { text: "" },
      { text: "The night I ran again, it hummed and glowed" },
      { text: "and spilled its brightest circle on the road." },
      { text: "Streetlights can't talk. But as I passed below," },
      { text: "it wrote one word in shadow: \"...slow.\"" },
    ],
  },
  {
    id: "quiet/caught-it-small",
    kind: "quiet",
    form: "verse",
    band: "small",
    mood: "steady",
    slots: [],
    lines: [
      { text: "Three weeks-ish of nothing. Not epic. Not vast." },
      { text: "Just a pause, like a comma, that quietly passed." },
      { text: "The street didn't panic. The hill didn't cry." },
      { text: "The mailbox assumed I was walking. (A lie.)" },
      { text: "" },
      { text: "I came back before the dust settled in," },
      { text: "before the couch even printed my skin." },
      { text: "The street said, \"You're late.\" I said, \"Barely. I'm here.\"" },
      { text: "(Catch a quiet while it's small, or it grows for a year.)" },
    ],
  },
];
