import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "route-champion/worn-myself-in",
    kind: "route-champion",
    form: "verse",
    band: "any",
    mood: "steady",
    slots: ["count"],
    lines: [
      { text: "There's a loop through this town that I've run {count} times." },
      { text: "It knows me like bells know their favorite chimes." },
      { text: "It hides the same pothole (I hop it asleep)," },
      { text: "same dog, same hello, same hedge grown deep." },
      { text: "" },
      { text: "Strangers see streets there. The loop and I grin." },
      { text: "It's not streets. It's a groove that I've worn myself in." },
      { text: "The earth has my orbit on file, like the moon's." },
      { text: "(We're both going nowhere. Importantly. Soon.)" },
    ],
  },
  {
    id: "route-champion/naming-the-orbit",
    kind: "route-champion",
    form: "verse",
    band: "any",
    mood: "steady",
    slots: ["name", "km", "count"],
    lines: [
      { text: "Astronomers name every orbit they find," },
      { text: "so here's mine, official, recorded and signed:" },
      { text: "{name}.", align: "center" },
      { text: "One loop, {km} kilometers of bend," },
      { text: "run {count} times, end to happy end." },
      { text: "" },
      { text: "Planets show off. But we regulars know:" },
      { text: "(the round-and-round runners make seasons. Ask snow.)" },
    ],
  },
  {
    id: "route-champion/the-block-is-talking",
    kind: "route-champion",
    form: "verse",
    band: "any",
    mood: "absurd",
    slots: ["count"],
    lines: [
      { text: "{count} times around the same block." },
      { text: "The block has started to talk." },
      { text: "Not loudly. It mutters. A curb-to-curb hum:" },
      { text: "\"Here comes our kid. Right on time. Here they come.\"" },
      { text: "" },
      { text: "The fences all know me. The gates never squeak." },
      { text: "The puddles reflect me my best twice a week." },
      { text: "A stranger once shortcut my loop on a jog." },
      { text: "(The block tripped him gently. You're welcome. — The Dog)" },
    ],
  },
  {
    id: "route-champion/autopilot",
    kind: "route-champion",
    form: "verse",
    band: "any",
    mood: "quiet",
    slots: ["count", "weekday"],
    coda: {
      requires: "shoes",
      lines: [
        { text: "P.S. These shoes trained alone once, a long quiet spell." },
        { text: "A loop this well-worn? They could run it as well." },
      ],
    },
    lines: [
      { text: "My shoes could run this one alone by now —" },
      { text: "left at the oak, where the hedges allow," },
      { text: "right at the corner the puddle patrols," },
      { text: "and home by the field with the practicing moles." },
      { text: "" },
      { text: "{count} laps of the very same song," },
      { text: "and any old {weekday}, they hum it along." },
      { text: "One day I'll doze off mid-lap, and I swear," },
      { text: "I'll wake on my porch. (The shoes know the fare.)" },
    ],
  },
  {
    id: "route-champion/third-try",
    kind: "route-champion",
    form: "verse",
    band: "small",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "Three times isn't many, the mapmakers scoff." },
      { text: "But three's when a route takes its stranger-suit off." },
      { text: "Once is a visit. And twice is a test." },
      { text: "But three times? You're friends. You can stay. You can rest." },
      { text: "" },
      { text: "By spring we'll be four, then eleven, then more." },
      { text: "The route's put my name on a leaf by its door." },
      { text: "Routes choose their runners. It's them who decide." },
      { text: "(I got chosen third try. Some wait years. Local pride.)" },
    ],
  },
  {
    id: "route-champion/the-crown-of-laps",
    kind: "route-champion",
    form: "verse",
    band: "large",
    mood: "triumphant",
    slots: ["count"],
    lines: [
      { text: "{count} laps! The loop wears a crown!" },
      { text: "Champion circuit of this side of town!" },
      { text: "The pigeons hold banners (they're crumbs, it's the thought)," },
      { text: "the hydrant salutes me the way it's been taught." },
      { text: "" },
      { text: "Reporters may ask how a legend is built:" },
      { text: "same corner, same puddle, same lean, same tilt," },
      { text: "same loop until loop and the kid are the same." },
      { text: "(The crown's made of laps. And it fits! That's the fame.)" },
    ],
  },
];
