import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "route-champion/one-chose-you",
    kind: "route-champion",
    form: "quip",
    band: "any",
    mood: "steady",
    slots: ["count", "name"],
    lines: [
      { text: "You have run {name}" },
      { text: "{count} times, and it knows your footfall now." },
      { text: "You didn't choose a favorite. One chose you." },
    ],
  },
  {
    id: "route-champion/no-longer-needs-directions",
    kind: "route-champion",
    form: "quatrain",
    band: "any",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "There is a route that no longer needs directions." },
      { text: "Your feet could run it while the rest of you sleeps." },
      { text: "Every crack is a word in a poem you have learned" },
      { text: "and never once grown tired of reciting." },
    ],
  },
  {
    id: "route-champion/back-so-soon",
    kind: "route-champion",
    form: "dialogue",
    band: "small",
    mood: "steady",
    slots: [],
    lines: [
      { text: "Back so soon? the route said, pleased, unsurprised.", voice: 1 },
      { text: "You know I always come back, you told it.", voice: 2 },
      { text: "I know the crack you trip on, it said, fondly.", voice: 1 },
      { text: "I have moved it slightly. Watch. See if you notice.", voice: 1 },
      { text: "You noticed, you said, tripping right on schedule.", voice: 2 },
      { text: "Good, said the route. I'd hate to lose the habit.", voice: 1 },
    ],
  },
  {
    id: "route-champion/be-it-known",
    kind: "route-champion",
    form: "notice",
    band: "small",
    mood: "steady",
    slots: ["count", "name"],
    lines: [
      { text: "BE IT KNOWN that {name}" },
      { text: "has hosted you {count} times and counting." },
      { text: "You are hereby its most persistent visitor," },
      { text: "granted tenure, a nod from every dog en route," },
      { text: "and the small pride of a path that knows your name." },
    ],
  },
  {
    id: "route-champion/what-it-still-hides",
    kind: "route-champion",
    form: "list",
    band: "medium",
    mood: "quiet",
    slots: [],
    lines: [
      { text: "Things your oldest route is still hiding from you:" },
      { text: "a side street you have never once turned down;", indent: 1 },
      { text: "the garden that blooms the weeks you're away;", indent: 1 },
      { text: "one bench it is saving for your slower years;", indent: 1 },
      { text: "a shortcut it has decided you don't need;", indent: 1 },
      { text: "and what it does at night, when no one's running.", indent: 1 },
    ],
  },
  {
    id: "route-champion/the-road-you-come-back-to",
    kind: "route-champion",
    form: "letter",
    band: "medium",
    mood: "quiet",
    slots: ["count", "name"],
    lines: [
      { text: "It's me. The road you always come back to." },
      { text: "" },
      { text: "You have given me a name after {count} laps:" },
      { text: "{name}" },
      { text: "and I wear it proudly, potholes and all." },
      { text: "The river path keeps asking who you are." },
      { text: "I tell it nothing. Let it find its own runner." },
      { text: "" },
      { text: "Jealously yours, — the route" },
    ],
  },
  {
    id: "route-champion/asks-nothing-of-you",
    kind: "route-champion",
    form: "spell",
    band: "large",
    mood: "steady",
    slots: ["name"],
    lines: [
      { text: "When your legs are tired of deciding, go" },
      { text: "to the one route that asks nothing of you:" },
      { text: "{name}." },
      { text: "You need not navigate. You need only arrive." },
      { text: "Let the familiar do the thinking for a while." },
      { text: "The oldest road forgives the tiredest runner." },
    ],
  },
  {
    id: "route-champion/the-same-good-loop",
    kind: "route-champion",
    form: "concrete",
    band: "large",
    mood: "steady",
    slots: [],
    lines: [
      { text: "out", align: "center" },
      { text: "along the river", align: "center" },
      { text: "up the one hill", align: "center" },
      { text: "across the top", align: "center" },
      { text: "down the far side", align: "center" },
      { text: "back by the shops", align: "center" },
      { text: "and home again —", align: "center" },
      { text: "the same good loop,", align: "center" },
      { text: "never once the same.", align: "center" },
    ],
  },
];
