import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "streak/a-chain-of-mornings",
    kind: "streak",
    form: "verse",
    band: "any",
    mood: "steady",
    slots: ["days", "weekday"],
    lines: [
      { text: "Day one was a {weekday}. Easy to do." },
      { text: "Day two followed day one. (That's how days accrue.)" },
      { text: "By day number four it had gotten a grip:" },
      { text: "a chain made of mornings I don't want to snip." },
      { text: "" },
      { text: "{days} days! Unbroken! A streak!" },
      { text: "My streak has a heartbeat. My streak's learned to speak." },
      { text: "It wakes me at dawn with a chain-rattle plea:" },
      { text: "\"Don't break me!\" ...The truth? It's the one keeping me." },
    ],
  },
  {
    id: "streak/dont-wake-it",
    kind: "streak",
    form: "verse",
    band: "any",
    mood: "absurd",
    slots: ["days"],
    coda: {
      requires: "the-watch",
      lines: [
        { text: "P.S. My watch is in on it. Every midnight, they meet." },
        { text: "They compare all their numbers. (I hear them. They cheat.)" },
      ],
    },
    lines: [
      { text: "Shhh — speak very softly. The streak is asleep." },
      { text: "It's had {days} mornings. It's in pretty deep." },
      { text: "If you wake it, it panics. It counts on its toes." },
      { text: "It frets about Tuesdays. It worries. It knows." },
      { text: "" },
      { text: "So tiptoe, tiptoe, don't rattle the door." },
      { text: "Whatever you do, don't count \"...four.\"" },
      { text: "Too late. It's awake now. It's lacing my shoe." },
      { text: "(A streak never rests. And it doesn't let YOU.)" },
    ],
  },
  {
    id: "streak/the-rain-test",
    kind: "streak",
    form: "verse",
    band: "any",
    mood: "triumphant",
    slots: [],
    lines: [
      { text: "One morning the rain came in curtains and sheets." },
      { text: "The gutters were bragging. The puddles claimed streets." },
      { text: "The couch cleared its throat and said, \"Stay! I'm so soft!\"" },
      { text: "The streak grabbed my laces and hauled me aloft." },
      { text: "" },
      { text: "So we went, streak and me, through the wet and the roar," },
      { text: "and came home like something the sea spat ashore." },
      { text: "The couch was still talking. The streak shut the door:" },
      { text: "\"He's mine until further notice. Don't call anymore.\"" },
    ],
  },
  {
    id: "streak/mornings-on-a-string",
    kind: "streak",
    form: "list",
    band: "any",
    mood: "quiet",
    slots: ["days", "weekday"],
    lines: [
      { text: "Mornings my streak has collected so far:" },
      { text: "a Monday (reluctant); a Tuesday (bizarre);", indent: 1 },
      { text: "a foggy one (spooky); a windy one (loud);", indent: 1 },
      { text: "one beautiful weirdo with only one cloud;", indent: 1 },
      { text: "and a {weekday} that strutted like a star.", indent: 1 },
      { text: "" },
      { text: "{days} mornings, strung on a string." },
      { text: "Don't touch. Don't breathe. Don't sneeze. Don't swing." },
      { text: "You're wondering what happens if one falls out?" },
      { text: "(So am I. That's what mornings are now about.)" },
    ],
  },
  {
    id: "streak/the-calendar-is-nervous",
    kind: "streak",
    form: "verse",
    band: "large",
    mood: "triumphant",
    slots: ["days"],
    lines: [
      { text: "I used to obey the calendar's grid —" },
      { text: "gray box after gray box. I did what it bid." },
      { text: "Now {days} boxes in one long row" },
      { text: "have sneaker-prints stamped on them. Look at them glow." },
      { text: "" },
      { text: "The calendar's nervous. It straightens its page." },
      { text: "It counts what I've colored. It feels its own age." },
      { text: "\"How long will this go on?\" it asked me last night." },
      { text: "I flipped to next month, and I said, \"Sit tight.\"" },
    ],
  },
  {
    id: "streak/the-trophy-for-boring",
    kind: "streak",
    form: "verse",
    band: "any",
    mood: "steady",
    slots: ["days"],
    lines: [
      { text: "Want to know how to run every day?" },
      { text: "Don't be spectacular. Not in one bone." },
      { text: "Run boring. Run tiny. Run \"kind of okay.\"" },
      { text: "Spectacular quits when it's out on its own." },
      { text: "" },
      { text: "{days} straight! And each one was small." },
      { text: "Small stacked upon small upon small got this tall." },
      { text: "The trophy for boring is fun to receive:" },
      { text: "you get one each morning, by choosing to leave." },
    ],
  },
];
