import type { PoemSpec } from "./forms";

export const POEMS: readonly PoemSpec[] = [
  {
    id: "streak/does-not-thank-you",
    kind: "streak",
    form: "quip",
    band: "any",
    mood: "absurd",
    slots: ["days"],
    lines: [
      { text: "{days} days in a row. The streak does not thank you." },
      { text: "It only asks, with quiet menace, about tomorrow." },
      { text: "Rest is a word it refuses to learn." },
    ],
  },
  {
    id: "streak/a-small-god",
    kind: "streak",
    form: "quatrain",
    band: "any",
    mood: "absurd",
    slots: [],
    lines: [
      { text: "The streak is a small god with a simple rule." },
      { text: "It does not care for reasons. It counts." },
      { text: "Miss one dawn and it forgets your name entirely," },
      { text: "and every day you gave it turns to smoke." },
    ],
  },
  {
    id: "streak/did-we-run-today",
    kind: "streak",
    form: "dialogue",
    band: "small",
    mood: "absurd",
    slots: [],
    lines: [
      { text: "Did we run today? the streak inquired, again.", voice: 1 },
      { text: "It's ten at night, you said. It's raining sideways.", voice: 2 },
      { text: "I heard no run in that, the streak observed.", voice: 1 },
      { text: "I have counted eight hundred. I do not stop for weather.", voice: 1 },
      { text: "Fine, you said, and found your shoes by feel.", voice: 2 },
      { text: "The streak said nothing, smug, and made it eight-oh-one.", voice: 1 },
    ],
  },
  {
    id: "streak/by-order-of-the-streak",
    kind: "streak",
    form: "notice",
    band: "small",
    mood: "absurd",
    slots: ["days"],
    lines: [
      { text: "BY ORDER OF THE STREAK, now {days} days strong:" },
      { text: "All rest days are hereby rescheduled to never." },
      { text: "Illness is not recognized. Weather is not recognized." },
      { text: "The management (you) cannot be reached for appeal." },
      { text: "Signed, the number, which only knows how to grow." },
    ],
  },
  {
    id: "streak/terms-and-conditions",
    kind: "streak",
    form: "list",
    band: "medium",
    mood: "absurd",
    slots: [],
    lines: [
      { text: "Terms and conditions of the unbroken streak:" },
      { text: "one run a day, no smaller than a shrug;", indent: 1 },
      { text: "holidays included, especially those;", indent: 1 },
      { text: "the run before the party, or after, but a run;", indent: 1 },
      { text: "no doctor's note accepted, ever, for any reason;", indent: 1 },
      { text: "and no discussion, none, of the word enough.", indent: 1 },
    ],
  },
  {
    id: "streak/a-very-heavy-gift",
    kind: "streak",
    form: "letter",
    band: "medium",
    mood: "absurd",
    slots: ["days"],
    lines: [
      { text: "You think I don't notice the days you resent me." },
      { text: "" },
      { text: "I do. I am {days} days of noticing, in fact." },
      { text: "I ask for so little: everything, daily, forever." },
      { text: "I am not a burden. I am a very heavy gift." },
      { text: "One day you'll thank me. That day is not today." },
      { text: "" },
      { text: "Devotedly, insatiably, yours — the streak" },
    ],
  },
  {
    id: "streak/what-it-eats",
    kind: "streak",
    form: "spell",
    band: "large",
    mood: "steady",
    slots: [],
    lines: [
      { text: "Speak to the day you do not want to run:" },
      { text: "tell it you will go small, and mean it, and go." },
      { text: "A slow mile keeps the chain the same as a fast one." },
      { text: "The streak cannot tell effort from arrival." },
      { text: "So give it arrival. That is all it eats." },
      { text: "Feed it once. Then close the door on its wanting." },
    ],
  },
  {
    id: "streak/the-bright-chain",
    kind: "streak",
    form: "concrete",
    band: "large",
    mood: "absurd",
    slots: [],
    lines: [
      { text: "day", align: "center" },
      { text: "and day", align: "center" },
      { text: "and day and day", align: "center" },
      { text: "and day and day and day", align: "center" },
      { text: "one missing link", align: "center" },
      { text: "and the whole", align: "center" },
      { text: "bright chain", align: "center" },
      { text: "comes apart", align: "center" },
      { text: "in your hands.", align: "center" },
    ],
  },
];
